<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_locationConfig_ticketButton</name>
   <tag></tag>
   <elementGuidId>88bd6a3e-2e78-4312-8cc1-46464828b42f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.EventSeatLocation_sectionOverviewCardMenu__HNNRg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = '⋮' or . = '⋮')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6a090c0-37e6-4e2c-8465-81d7803c157d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52c90bab-d5d1-4462-a89b-3573b1ed7368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_sectionOverviewCardMenu__HNNRg</value>
      <webElementGuid>369983d6-eb64-4d47-9b4b-a08d73a19613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Section options</value>
      <webElementGuid>b92855fd-f708-49d4-ba7f-0426b99486d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea195d8d-addf-49f8-aaca-f36a9b201157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3cb01ef4-6ee4-4bb6-add8-9e0fe3fa3c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>⋮</value>
      <webElementGuid>21baabe5-a9a4-4c6a-8756-bd3fcbf29475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;EventSeatLocation_eventSeatLocationWrapper__jIGpH&quot;]/div[@class=&quot;EventSeatLocation_mainContent__WswuK&quot;]/div[@class=&quot;EventSeatLocation_seatConfigSection__n5+3E&quot;]/div[@class=&quot;EventSeatLocation_leftPanel__5HknY&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewBlock__KkIcz&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewList__OJmca EventSeatLocation_sectionOverviewListRow__1N-5M&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardItem__kEXd3&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardHeader__QdFq-&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardActions__JvpnP&quot;]/button[@class=&quot;EventSeatLocation_sectionOverviewCardMenu__HNNRg&quot;]</value>
      <webElementGuid>24717fa4-978a-4d2f-b906-4d249a56812b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>e41f3952-7bb0-4d65-8fac-5805b8127057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>c1f67219-460e-4242-9320-b533447ccb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Tier 1'])[1]/following::button[1]</value>
      <webElementGuid>c80564a0-8fe5-46f5-b81e-d6384461734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Section'])[1]/following::button[1]</value>
      <webElementGuid>9754ff9f-3416-4346-9dde-5011a06f78fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$40.00'])[1]/preceding::button[1]</value>
      <webElementGuid>ebebc797-2758-4584-90fa-b9469ca48848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section Details'])[1]/preceding::button[1]</value>
      <webElementGuid>4529675c-428a-4183-803f-b28b6a831d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='⋮']/parent::*</value>
      <webElementGuid>ddccbd31-f8c9-4304-925a-3f220c90b12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>d2731c7d-15f3-4e96-9705-e7af4199f6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '⋮' or . = '⋮')]</value>
      <webElementGuid>c3ad526d-399e-4df4-abe7-473ce3a4b2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
