<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ticketingPaid_couponSave</name>
   <tag></tag>
   <elementGuidId>39a49753-c5fc-418d-97aa-003ae21bd40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TicketAndPricing_couponEditActions__Efdbb > button.TicketAndPricing_secondaryButton__NcQ-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a0ddd28-3730-4e3d-ac8e-1ac35e2d5040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0d60bdf-7a6d-442e-9202-505bcadc47e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_secondaryButton__NcQ-7</value>
      <webElementGuid>b49ad97f-67cd-4c43-a0b8-6e046572e263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save coupon</value>
      <webElementGuid>c007a01e-a787-4c2f-bde3-a23dded0643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1794c387-d559-488a-a4e7-9a5f522d747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-paid&quot;)/section[@class=&quot;TicketAndPricing_section__yLPcg TicketAndPricing_sectionPromo__PPwFw&quot;]/div[@class=&quot;TicketAndPricing_couponWrap__HoPEV&quot;]/div[@class=&quot;TicketAndPricing_couponList__8l8Nc&quot;]/div[@class=&quot;TicketAndPricing_couponItem__S6Je+&quot;]/div[@class=&quot;TicketAndPricing_couponEditForm__f1L6H&quot;]/div[@class=&quot;TicketAndPricing_couponEditActions__Efdbb&quot;]/button[@class=&quot;TicketAndPricing_secondaryButton__NcQ-7&quot;]</value>
      <webElementGuid>e7810ef7-35d3-4df1-ae5b-dfaf15ffcb8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>1c2b2d70-866f-4708-90e4-7842cdd5db9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/section[2]/div[2]/div/div/div/div[6]/button</value>
      <webElementGuid>d689c65c-6b61-4928-9d65-5e78efcd2579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scope'])[1]/following::button[1]</value>
      <webElementGuid>62716bc4-1855-47df-a352-3c93bdd49936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max: 100%'])[1]/following::button[1]</value>
      <webElementGuid>b54f89aa-1ecb-4fce-a9b1-20a415d256d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>4b1c1f38-c239-4125-873d-d346403ba9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing Preview'])[1]/preceding::button[2]</value>
      <webElementGuid>e25229cf-ff0e-4ad7-8c3c-1055404d735f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>811f9184-94f3-44be-ba03-64902c02852a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>086ee812-2c4b-4574-9a8d-7be35db682b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>025c0fdd-cbe3-4bf1-beb4-14b6c1d9373b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
