<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_locationConfig_ticketConfigure</name>
   <tag></tag>
   <elementGuidId>94674c4a-ced9-48b4-8ecb-8629f4eddc25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.EventSeatLocation_sectionOverviewCardDropdownItem__WIML2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Configure' or . = 'Configure')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32fcc86e-2119-4133-8bf7-a6a86d20fd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3767658e-7c42-413e-aacb-d2d44283d266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>56a73287-d9d7-482a-b73b-f8b3ba5a098b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_sectionOverviewCardDropdownItem__WIML2</value>
      <webElementGuid>1729038b-db1d-459a-ba8c-bcee790e48f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configure</value>
      <webElementGuid>b3bc0b29-1e65-4853-a98d-dd14f99f8254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;EventSeatLocation_eventSeatLocationWrapper__jIGpH&quot;]/div[@class=&quot;EventSeatLocation_mainContent__WswuK&quot;]/div[@class=&quot;EventSeatLocation_seatConfigSection__n5+3E&quot;]/div[@class=&quot;EventSeatLocation_leftPanel__5HknY&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewBlock__KkIcz&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewList__OJmca EventSeatLocation_sectionOverviewListRow__1N-5M&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardItem__kEXd3&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardHeader__QdFq-&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardActions__JvpnP&quot;]/div[@class=&quot;EventSeatLocation_sectionOverviewCardDropdown__O9+Ol&quot;]/button[@class=&quot;EventSeatLocation_sectionOverviewCardDropdownItem__WIML2&quot;]</value>
      <webElementGuid>8600e0da-de14-43ab-a033-410d35a60d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>ff900718-c409-452f-ab62-be0eaf1a1f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div/div[2]/div[2]/div/div/div/div/button</value>
      <webElementGuid>ac1ff4ef-10eb-4510-933e-695990988df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⋮'])[1]/following::button[1]</value>
      <webElementGuid>94cdd00e-bb8d-46bb-8342-3b6a5236ea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Tier 1'])[1]/following::button[2]</value>
      <webElementGuid>5db5c430-b2a5-41cd-aac8-dd967a8aec43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>78e7220f-53e5-46ce-a09a-62e95642eb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$40.00'])[1]/preceding::button[2]</value>
      <webElementGuid>0f4e5307-2c81-4c81-bb6f-96f003867987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Configure']/parent::*</value>
      <webElementGuid>102e3469-b97f-4695-ae71-93c87467a5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/button</value>
      <webElementGuid>b75b4978-c0de-45ab-bf95-9bff7a92c65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Configure' or . = 'Configure')]</value>
      <webElementGuid>cf090132-d8f7-42a1-b632-f8663afe467c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
