<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_locationConfig_saveSection</name>
   <tag></tag>
   <elementGuidId>41efd096-8e78-49ec-8526-e7fb17dfb73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.EventSeatLocation_primaryButton__WFp8q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Save Section' or . = 'Save Section')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd237342-2342-463f-912c-07b824c8c135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47e2b2af-8e88-4ddd-9f50-6d5a5d79a3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_primaryButton__WFp8q</value>
      <webElementGuid>fe6ba6f1-5c72-442a-88fd-5a14b5aed564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Section</value>
      <webElementGuid>9ef86d5b-1ba8-42e4-b03b-0d2fbead75ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;EventSeatLocation_eventSeatLocationWrapper__jIGpH&quot;]/div[@class=&quot;EventSeatLocation_mainContent__WswuK&quot;]/div[@class=&quot;EventSeatLocation_seatConfigSection__n5+3E&quot;]/div[@class=&quot;EventSeatLocation_rightPanel__WDcaJ&quot;]/div[@class=&quot;EventSeatLocation_configCard__riyS8&quot;]/div[@class=&quot;EventSeatLocation_configureForm__X0p9U&quot;]/div[@class=&quot;EventSeatLocation_configureFormActions__SVkrK&quot;]/button[@class=&quot;EventSeatLocation_primaryButton__WFp8q&quot;]</value>
      <webElementGuid>d0ef49ee-a6c8-4303-8a94-610785df7c49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[31]</value>
      <webElementGuid>7179bedd-1ec1-4e8d-b43c-0952ea94a036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div[2]/div/div[2]/div[7]/button[2]</value>
      <webElementGuid>a43e1c76-132f-433e-8461-7687f8eaa16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>90cb3efc-fb72-4d66-b177-a67478bdb289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::button[2]</value>
      <webElementGuid>3667d2de-916e-486c-9fb8-764a36b0305b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft automatically saved'])[1]/preceding::button[1]</value>
      <webElementGuid>1e9f9df0-934f-464d-96ec-ebf8725fdd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/preceding::button[1]</value>
      <webElementGuid>b00d6953-afbb-48cc-a65f-c1ec6f71f363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Section']/parent::*</value>
      <webElementGuid>ad78288a-a971-4622-a721-25a663764f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button[2]</value>
      <webElementGuid>7b4b8df8-5d34-4ee2-b252-3713dba3dbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Save Section' or . = 'Save Section')]</value>
      <webElementGuid>8794ba09-a863-44b9-9902-613331e0da73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
