<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_tierMaxTicket</name>
   <tag></tag>
   <elementGuidId>075afe5e-59ec-4607-8310-2736dc9e3864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tier-max-per-booking-tier-new-1776338654981</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'tier-max-per-booking') and @type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>414e1b66-43ec-4220-83e8-3b4a8b3db3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tier-max-per-booking-tier-new-1776338654981</value>
      <webElementGuid>554991e6-ea21-4cf2-b7b7-8bfa9df6af3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej </value>
      <webElementGuid>6998b54c-ea67-4708-81f9-5fc35f87282e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0417bb9d-ec0e-49ec-a699-599622b65ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>873566e8-c177-4026-b26a-7667f0e15cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>329cf2a1-643a-4cde-b604-b8a45c4dc89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d55b9d48-bd31-4c2e-b604-4800f2e9528f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unlimited</value>
      <webElementGuid>ca35fc9c-3644-4059-bb9d-1198e3940cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71a37463-357c-40da-8d95-261cbdee4121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tier-max-per-booking-tier-new-1776338654981&quot;)</value>
      <webElementGuid>9b1ff3c6-8c3e-4fef-8245-6d5539bbbf08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tier-max-per-booking-tier-new-1776338654981']</value>
      <webElementGuid>122e0845-7b90-45e2-b0fc-c3c31ac07f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/div[2]/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>9a2a9a82-f189-4907-a5bd-a2c99b853ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>57ad8a5c-7f36-405e-aede-df637d1bcdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tier-max-per-booking-tier-new-1776338654981' and @type = 'number' and @placeholder = 'Unlimited']</value>
      <webElementGuid>7509c3ec-a378-4e9b-812e-a786070a5575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
