<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_couponValue</name>
   <tag></tag>
   <elementGuidId>0723f5ba-1e5d-4754-85c0-ce862121f300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon-value-c-1776339400167</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'coupon-value') and @type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36d250ff-19c8-4fd5-b93c-f0e98845180f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-value-c-1776339400167</value>
      <webElementGuid>d9b82f87-b7ec-4182-b00b-1576f2347498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej</value>
      <webElementGuid>c7897c29-3df6-4246-abd2-e68ea5005884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9e5b4e16-0767-44c9-ae88-b87a09071339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>5e563e82-908c-4bd2-8e5e-09e112628e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f3e7438c-f1ee-42ac-8025-267508d8e66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9863bf59-4c9b-41fe-815c-ec49bf1c76a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>coupon-value-hint-c-1776339400167</value>
      <webElementGuid>f794d73c-a64e-4d0d-bac4-1bde59bff7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b946a8c0-51b6-4caa-93c1-97981144e620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-value-c-1776339400167&quot;)</value>
      <webElementGuid>b8005dee-8cfb-4adc-ab5e-17609222843f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon-value-c-1776339400167']</value>
      <webElementGuid>cad3ad4b-d41f-4c32-9a01-360f33c1d3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/section[2]/div[2]/div/div/div/div[4]/input</value>
      <webElementGuid>60a26075-8499-41bf-8981-9b1d7094e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>23501c2f-76c5-4ddd-8363-f67dbd51d089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'coupon-value-c-1776339400167' and @type = 'number']</value>
      <webElementGuid>f55af287-cc4f-4210-9a06-16416b5f2c34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
