<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_locationConfig_Row range(from)</name>
   <tag></tag>
   <elementGuidId>0a9db94a-0f7e-4222-b3b3-d33e52389e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#configure-row-from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='configure-row-from-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2d3795a-ec85-4fa2-967c-540006fa1fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>configure-row-from</value>
      <webElementGuid>2c21c2f6-bec6-41a2-b54a-12fa0afbd8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a02af609-3fc7-4857-bb6b-9acdb9b5c256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_configInput__TZVY3</value>
      <webElementGuid>9bf002a8-dee9-4612-a857-a9829b290d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. A</value>
      <webElementGuid>80b673f1-fb90-43bc-87f4-3f00740cb450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b0d3c78-5dda-458f-b520-535e9e2e6a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ffab6870-919c-4d06-bd3a-fc6943aafdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>configure-row-hint</value>
      <webElementGuid>da41c44e-d24c-4c13-97cc-2e9220f41f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configure-row-from&quot;)</value>
      <webElementGuid>9f525804-b986-41ce-b46d-1ced823308bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='configure-row-from']</value>
      <webElementGuid>f487878e-bfab-49fa-af9f-d55503b58c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>eb804c6f-ec3c-45a5-a8a2-cd522aabcb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>6da47e63-368d-4ce6-9c85-89b1f33a4ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'configure-row-from' and @type = 'text' and @placeholder = 'e.g. A']</value>
      <webElementGuid>2c36cf41-d146-4f22-b195-ecfd5d91065f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
