<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_couponDesc</name>
   <tag></tag>
   <elementGuidId>fb9582c8-2e43-4e94-8c26-1659c6159ebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon-desc-c-1776339400167</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'coupon-desc') and @type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6b2a17e-e4a3-49bb-9b61-56a710ce35c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-desc-c-1776339400167</value>
      <webElementGuid>2c07ec69-3c12-4570-a512-6132f61db924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej</value>
      <webElementGuid>f7f822cb-f30b-4afc-841a-41f046860a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fc48b9d-6146-4c33-a4b2-5f9e4b05e77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 10% off all tickets</value>
      <webElementGuid>5323de04-d724-47ba-9a7f-e224aab48f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>48972c6a-6e8d-495f-b330-6122c24890b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Promotional code description</value>
      <webElementGuid>7ad98e66-4bb1-47a7-89cf-610def61d24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>coupon-desc-hint-c-1776339400167</value>
      <webElementGuid>00836a35-5104-4053-834a-ed6d3e7a7fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-desc-c-1776339400167&quot;)</value>
      <webElementGuid>3e1a2288-3e93-4e6e-a790-00e87abcdf7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon-desc-c-1776339400167']</value>
      <webElementGuid>13f4894f-e026-4835-be7c-60dc15f824f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/section[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>38aaa316-1b2a-4360-9392-0c15ef8d4ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>151b335f-14d5-4065-b16a-68796aad8294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'coupon-desc-c-1776339400167' and @type = 'text' and @placeholder = 'e.g. 10% off all tickets']</value>
      <webElementGuid>68e9463d-2c1f-4caf-baf4-463e614a2ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
