<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_tierQuantity</name>
   <tag></tag>
   <elementGuidId>29c5db2a-4bed-4874-8c58-65195756a789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tier-qty-tier-new-1776338654981</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'tier-qty') and @type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71c616dd-e30c-43dc-b584-cd8db553e615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tier-qty-tier-new-1776338654981</value>
      <webElementGuid>40acdae7-bb03-4be4-a908-913684f6d80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej </value>
      <webElementGuid>b89e48d8-18d2-4f88-a4d7-508fbd4cb92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4a5f82a2-0a71-47d4-a836-6327072aca46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5f4bcdc5-22a1-4559-9100-50dde16ebbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ef5685ad-7224-47a4-a99c-4eae9e1b1a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47614b92-382c-4c87-b907-a2c61068ca05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e76ad933-49e2-4e46-9479-153ac90b863b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tier-qty-tier-new-1776338654981&quot;)</value>
      <webElementGuid>e4ffbdc3-5b50-4723-820b-8e41e708729f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tier-qty-tier-new-1776338654981']</value>
      <webElementGuid>690d582a-29a3-4806-87f3-4e5b93d741fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>9fb59cbb-5d58-41e9-9b7f-d22ad9c383b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>b4f718b6-6591-4351-bd75-357c555a7bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tier-qty-tier-new-1776338654981' and @type = 'number']</value>
      <webElementGuid>6d10d889-6e3c-41d4-8da1-90cb1ed1a400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
