<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_tierPrice</name>
   <tag></tag>
   <elementGuidId>b9bfdf24-7cca-4cbc-a12e-cc75a7ff855c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tier-price-tier-new-1776338654981</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'tier-price') and @type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d5bb891-1968-496c-89b3-0ce782c51c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tier-price-tier-new-1776338654981</value>
      <webElementGuid>59cb9d15-5644-4b43-a968-7f138232ef3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej </value>
      <webElementGuid>455bdc66-0de3-4714-b570-58077d490ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c03db68c-ba9b-40c7-914e-f9f205e15672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>dac1b3be-f78c-4fe9-92bf-e22013463b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>739a5a1c-b5bf-472a-9c42-8eecf70d31b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00 (set in Location)</value>
      <webElementGuid>ea9eb955-01fd-4182-b4d2-2f7ac25b2cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Price</value>
      <webElementGuid>e3713b21-5999-4b33-a4bc-304c7377f780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3f1ec38e-0481-4ced-8ee5-dce2330921ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0cabc8ab-454c-42ab-930f-b3015f678e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tier-price-tier-new-1776338654981&quot;)</value>
      <webElementGuid>e2d5d1b5-e35d-4567-bbbf-6d1e4ea4a809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tier-price-tier-new-1776338654981']</value>
      <webElementGuid>69a7bceb-9653-4403-9305-df31e66cb78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>ddaa786a-9e82-458d-a8b8-057ff9bd56af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fefb59e7-bcb0-4fc3-a016-f6591081d894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tier-price-tier-new-1776338654981' and @type = 'text' and @placeholder = '0.00 (set in Location)']</value>
      <webElementGuid>ccfec048-a97c-4b66-83a1-8cf5a8cf0eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
