<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_tierTicketName</name>
   <tag></tag>
   <elementGuidId>471415c5-f1cf-4923-8e97-253b2a18e967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tier-name-tier-new-1776338654981</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'tier-name') and @type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50a708f5-fb37-4f53-8f8d-51efdc3d7c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tier-name-tier-new-1776338654981</value>
      <webElementGuid>05d51345-4131-4631-8f35-fd84e339568d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej </value>
      <webElementGuid>0a80ee5e-4b7b-41ed-b80e-88e77e1da92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6197a3a5-6648-4b45-845c-4913c99da098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. General Admission</value>
      <webElementGuid>e12113b1-6c81-4561-8d26-05cb9a10f65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3953512e-0d21-4435-b9fb-cee29f68b146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>New Tier 1</value>
      <webElementGuid>c7ebeb4a-ae7a-4dbd-982d-fa3277ea8685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tier-name-tier-new-1776338654981&quot;)</value>
      <webElementGuid>e3c9ff20-7b85-4ed5-bf77-504ab05d7d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tier-name-tier-new-1776338654981']</value>
      <webElementGuid>cc65ba7f-9e31-45ea-801e-9f377596fe7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>664e90bb-7db9-4aa7-b482-5769f9874d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>703bcbb4-e3aa-4d8b-a877-7f40ef6a2adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tier-name-tier-new-1776338654981' and @type = 'text' and @placeholder = 'e.g. General Admission']</value>
      <webElementGuid>0b90ca83-5f0f-4b69-b23f-1ff34dbc489d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
