<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_locationConfig_Seat range(from)</name>
   <tag></tag>
   <elementGuidId>27b035e5-d20c-440a-95ba-421092ca9bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#configure-seat-from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='configure-seat-from-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f884c1b0-8c71-4d79-aea4-bcad47fb8ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>configure-seat-from</value>
      <webElementGuid>59b156b3-4701-4829-9af9-52c5e2de6c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d6b45155-74cf-4186-bd54-482a19762935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>34dfc535-0041-4bf9-ad09-98fb286726cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_configInput__TZVY3</value>
      <webElementGuid>ed432da0-faa4-430a-b429-b95b3ca92a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 1</value>
      <webElementGuid>afabf2a0-dc46-412d-b859-7537ba4be95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b3d1958-64b3-4972-bbed-014c5c5a8ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac4ceb25-3fa6-4386-9172-fc46d74cbf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configure-seat-from&quot;)</value>
      <webElementGuid>5e4f0e9a-b61a-4e4a-8ed3-74b314d7fa86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='configure-seat-from']</value>
      <webElementGuid>d065ea79-bc71-4ff5-a663-fa02c8b4ad67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div[2]/div/div[2]/div[3]/div/input</value>
      <webElementGuid>fc61eed6-7e60-4d90-a838-56ed8cea3086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c5d49628-b6f2-45b9-a16c-d1e38261e76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'configure-seat-from' and @type = 'number' and @placeholder = 'e.g. 1']</value>
      <webElementGuid>c5f4a227-8f02-48eb-9e05-6a5e90c9075f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
