<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_locationConfig_Seat range(to)</name>
   <tag></tag>
   <elementGuidId>3dadb497-46e2-4640-a4b8-9f26ce353652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#configure-seat-to</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='configure-seat-to-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8ab92fa-dbcd-46a9-aa7f-383c9c60981c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>configure-seat-to</value>
      <webElementGuid>467e7d25-25b3-439d-89b9-34dd3d2c0ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>26bdde99-6bf6-4d71-92ba-7841b1086540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7bf11a30-1ab9-44b7-aaeb-4bb17530dc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_configInput__TZVY3</value>
      <webElementGuid>6b8090da-95da-4eaf-b475-ae1c9efe076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 24</value>
      <webElementGuid>d14a160e-835c-4f15-bd25-a212561e2ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00384bda-aaa5-4a12-80fc-ccb0c2216f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1fbc5e0d-6873-4e42-96b5-0a4b49886c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configure-seat-to&quot;)</value>
      <webElementGuid>deea88f4-c21e-4a3d-b592-18df51019646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='configure-seat-to']</value>
      <webElementGuid>b5018aa0-b940-402f-a4d4-50f71cdec1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div[2]/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>1e9e9f3b-4b42-4f08-81d1-b3ec74ed37d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>14a04e4a-5082-46e2-afdf-660494c9a8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'configure-seat-to' and @type = 'number' and @placeholder = 'e.g. 24']</value>
      <webElementGuid>81f662e3-0626-4868-8252-65da68304c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
