<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_locationConfig_Row range(to)</name>
   <tag></tag>
   <elementGuidId>373417b2-a3b0-41ea-9443-210a2d6d1f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#configure-row-to</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='configure-row-to-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7121708-9a98-4a0f-9748-0287750a8f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>configure-row-to</value>
      <webElementGuid>3b3864a0-0473-4e4a-bb08-84cfb5248f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6521b7e0-07c7-46e2-88c8-38e9d8921946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_configInput__TZVY3</value>
      <webElementGuid>37734d74-1a78-49e2-9229-4fbfd49865e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. P</value>
      <webElementGuid>b1f96cd3-907f-4e48-a406-4c31baa983f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fddc4639-a143-4aec-8393-a96cc89e08d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4e0620ad-c99e-416f-bec9-69553b504efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>configure-row-hint</value>
      <webElementGuid>9c046fb0-fc12-43f4-8a73-5c998dc8b1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configure-row-to&quot;)</value>
      <webElementGuid>61cd3645-e419-407a-92e2-bf683fbe96f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='configure-row-to']</value>
      <webElementGuid>f699e581-30a2-495c-9181-ef04befd5bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[5]/div[2]/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>b5d09095-86ca-402a-85ea-2ac7972f58d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>752fc8a2-9861-4b8a-8605-e88bdb2180e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'configure-row-to' and @type = 'text' and @placeholder = 'e.g. P']</value>
      <webElementGuid>1b6e4d55-21ab-4904-b67d-c5b511791e7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
