<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ticketingPaid_couponCode</name>
   <tag></tag>
   <elementGuidId>a6398101-c287-437c-8875-e4043f24ab83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon-code-c-1776339400167</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'coupon-code') and @type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6354f2e8-b4a9-4fe7-ac6a-fe9dc5949f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-code-c-1776339400167</value>
      <webElementGuid>0c479df5-d909-40b1-ab27-1447aad34c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej</value>
      <webElementGuid>e41c44d7-8308-483e-a9d3-d7c54c6d8c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d644704-8fe1-4ee4-b78e-ea0648d4d0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. SAVE10</value>
      <webElementGuid>b43f2175-af7f-47f8-a90e-08c6d5cc0dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-code-c-1776339400167&quot;)</value>
      <webElementGuid>d030829c-35fb-453f-ae8d-36671f79ad82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon-code-c-1776339400167']</value>
      <webElementGuid>d2b15b6b-0028-44d4-a84c-ea6436a72a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-paid']/section[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>8b2bf906-d1d4-48db-8d0d-abc8a738f4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>3f27f45b-83ee-4b4e-a639-ff4286a11c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'coupon-code-c-1776339400167' and @type = 'text' and @placeholder = 'e.g. SAVE10']</value>
      <webElementGuid>7faaec8a-9a17-4737-918d-4c2c9ca06bdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
