<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_eventLocation_selectionAddress</name>
   <tag></tag>
   <elementGuidId>d63fc75f-b5e5-481a-9479-9c235eebe873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Casablanca, MoroccoCasablanca, Casablanca-Settat' or . = 'Casablanca, MoroccoCasablanca, Casablanca-Settat')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.EventSeatLocation_addressSuggestionItem__bZqIL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7b4a738-3782-41b3-9cf6-0db865fe9e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07c38264-5105-4465-be42-d72df875249b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4414d150-0381-4cba-83d2-297f943559c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_addressSuggestionItem__bZqIL</value>
      <webElementGuid>5792b91b-044e-4f49-ae5e-ad18e515c2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casablanca, MoroccoCasablanca, Casablanca-Settat</value>
      <webElementGuid>a81b52b0-c0d1-4f71-960f-01e6537fc751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;EventSeatLocation_eventSeatLocationWrapper__jIGpH&quot;]/div[@class=&quot;EventSeatLocation_mainContent__WswuK&quot;]/div[@class=&quot;EventSeatLocation_formSection__UhFSH&quot;]/div[@class=&quot;EventSeatLocation_formGroup__Ex27Y&quot;]/div[@class=&quot;EventSeatLocation_addressInputWrapper__eZ4gz&quot;]/div[@class=&quot;EventSeatLocation_addressSuggestionsDropdown__qwyB0&quot;]/div[@class=&quot;EventSeatLocation_addressSuggestionItem__bZqIL&quot;]</value>
      <webElementGuid>6f77718f-b3a0-4169-a879-f6df1717acb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[3]/div[2]/div/div[2]/div</value>
      <webElementGuid>c78878a0-18a5-45cf-9c5a-68a0b8aca3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[4]</value>
      <webElementGuid>6ed25dff-c110-446c-926a-24db1ac125c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>9ce2d61b-7b3b-430a-bd9b-1c662ec02123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Casablanca, MoroccoCasablanca, Casablanca-Settat' or . = 'Casablanca, MoroccoCasablanca, Casablanca-Settat')]</value>
      <webElementGuid>dee2cab4-9870-4944-ad39-0d9381dc1b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
