<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_eventLocation_venueName</name>
   <tag></tag>
   <elementGuidId>f8dcd158-650e-4fc3-b2ac-a9f634508707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='venueName-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#venueName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a531b48-5666-4841-a08e-7fec28338d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>venueName</value>
      <webElementGuid>b4043071-ab67-44f8-bd58-b50d7ded9aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d55c1bd0-5512-4fa0-9ebf-1392ee130ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_input__SE-Et </value>
      <webElementGuid>ad5a8229-d224-4e26-9afc-0a056b3b99f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Convention Center</value>
      <webElementGuid>105747dc-d0f7-43db-923a-49d7cdf03531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>e29a8258-529b-47f1-baa4-996026f369c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9afcf84f-c069-41bc-963c-a3df94e2a435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;venueName&quot;)</value>
      <webElementGuid>995824ce-e9e5-4e10-b12b-145f929d38bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='venueName']</value>
      <webElementGuid>aa9fe58e-1d83-419e-b459-7ba603c9da32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>835c177d-2903-4ff8-bbf6-8779bf3df19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4df59529-e282-407a-a53c-ed3e58dbda66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'venueName' and @type = 'text' and @placeholder = 'e.g. Convention Center']</value>
      <webElementGuid>fdbb82ce-d44d-4728-a898-4df64981d3ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
