<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_eventLocation_seatMap</name>
   <tag></tag>
   <elementGuidId>c954b392-c61e-4f4c-9042-09654654e751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='seatmap-select-0-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#seatmap-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b400a892-7df2-4b34-bd50-25a6b2fdcd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seatmap-select</value>
      <webElementGuid>6245d126-eec8-41e6-a0da-46f1d5809290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventSeatLocation_seatMapSelect__E6W7z </value>
      <webElementGuid>f52ae506-f02d-4c08-b9c1-e4812ea92f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select seat map</value>
      <webElementGuid>dcc95077-f7f2-423b-a1cd-ebc441822a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35729311-2644-4460-8ed9-f41458cab876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a seat mapKirkland Performance Centeryellow boxlayout newYellow BoxThe MoonTesting</value>
      <webElementGuid>c88ac7e2-c9d5-4c7e-a1e9-196cb686bc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seatmap-select&quot;)</value>
      <webElementGuid>241e3e32-28dd-4c4d-9234-909fb458aad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='seatmap-select']</value>
      <webElementGuid>798ec7e7-1bfc-4def-b8e8-38e76c793e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>b6817368-b4fb-4f22-8721-f7e03aed9dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From list'])[1]/following::select[1]</value>
      <webElementGuid>4981329f-d154-4519-a19d-b6178d250191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seat Map'])[1]/following::select[1]</value>
      <webElementGuid>8c70b6d6-a4f1-442c-b6f3-d6efd39f7dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A copy will be created for this event when you save.'])[1]/preceding::select[1]</value>
      <webElementGuid>cd1b2b2c-44a9-48c0-bb00-1fe56b3cb949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload seat layout image'])[1]/preceding::select[1]</value>
      <webElementGuid>72912496-e6f7-428f-9b69-a0337358dff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cf7d8882-7e6c-4ac1-9c89-3523e8070252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'seatmap-select' and (text() = 'Select a seat mapKirkland Performance Centeryellow boxlayout newYellow BoxThe MoonTesting' or . = 'Select a seat mapKirkland Performance Centeryellow boxlayout newYellow BoxThe MoonTesting')]</value>
      <webElementGuid>58234f48-181f-4380-82e1-58ccc4edc0e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
