<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Item_modal</name>
   <tag></tag>
   <elementGuidId>7c558f8a-5b76-4967-9052-11a87a9706c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'FoodAndBeverages_modalContent')]//button[contains(@class, 'FoodAndBeverages_modalBtnPrimary')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.FoodAndBeverages_modalBtnPrimary__GonsF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98ef0c82-9d6e-4ed1-9a1e-6fcbbd299a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5596dbc7-6e06-43a8-9f69-dc5caef79e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FoodAndBeverages_modalBtnPrimary__GonsF</value>
      <webElementGuid>88d7825e-7c56-419a-9a3e-ec2a9c5f16bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Item</value>
      <webElementGuid>d01eca63-5f56-45d4-a542-21486f37c402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;FoodAndBeverages_foodAndBeveragesWrap__itNXT&quot;]/div[@class=&quot;FoodAndBeverages_modalOverlay__Z-31F&quot;]/div[@class=&quot;FoodAndBeverages_modalContent__P9MXO&quot;]/div[@class=&quot;FoodAndBeverages_modalActions__NQiiu&quot;]/button[@class=&quot;FoodAndBeverages_modalBtnPrimary__GonsF&quot;]</value>
      <webElementGuid>71dbda2e-5296-4820-a79b-ce0c35811ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[25]</value>
      <webElementGuid>aff65a9e-fc69-4b6d-af39-268adbd9fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>88780819-ae48-4045-96b7-12e76feb5069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>083579bf-f520-4dab-81c1-847ec3c25601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>d5cd8ed4-9841-4081-9944-72fa44136593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Item' or . = 'Add Item')]</value>
      <webElementGuid>cc0b98b5-9fa5-42b5-a624-ef852b80a76b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
