<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Stallvendoryopmail.com</name>
   <tag></tag>
   <elementGuidId>bd3b9024-8fb6-4395-8039-93cc2042bee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Stallvendor@yopmail.com' or . = 'Stallvendor@yopmail.com')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.FoodAndBeverages_existingVendorRow__XYDiU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14136a02-f798-4b7d-8504-32d2be7718ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d67fe29-11c2-4a76-8359-21ae72966e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FoodAndBeverages_existingVendorRow__XYDiU</value>
      <webElementGuid>30ea8824-4c19-4e5d-9851-662ded4b5372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stallvendor@yopmail.com</value>
      <webElementGuid>853bbcd0-0be7-4367-a344-540be465d867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;FoodAndBeverages_foodAndBeveragesWrap__itNXT&quot;]/div[@class=&quot;FoodAndBeverages_modalOverlay__Z-31F&quot;]/div[@class=&quot;FoodAndBeverages_modalContent__P9MXO&quot;]/div[@class=&quot;FoodAndBeverages_modalList__eu1b8&quot;]/button[@class=&quot;FoodAndBeverages_existingVendorRow__XYDiU&quot;]</value>
      <webElementGuid>c4110f58-e146-4e64-87ed-892f23f1762f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[25]</value>
      <webElementGuid>f44c9dbc-15d6-486b-a760-f0a5b7d16462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>2c001b5e-59fa-4167-a875-12649b9d92ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add from Existing'])[1]/following::button[1]</value>
      <webElementGuid>693ee066-4370-4fa9-9107-4436391dcdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New'])[1]/following::button[2]</value>
      <webElementGuid>c55e8c4f-efdc-4bc5-b42f-03fc7bb95c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>17637158-ea91-4068-844a-0fad55c143e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Stallvendor@yopmail.com' or . = 'Stallvendor@yopmail.com')]</value>
      <webElementGuid>36062bbf-acd0-4b50-83d2-3065b1cb9cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
