<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item name</name>
   <tag></tag>
   <elementGuidId>2aa6aa04-acb5-4578-aa91-ba0cc15b7648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new-item-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new-item-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cddb3f70-ce7a-4c58-b1e5-54fa90748e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-item-name</value>
      <webElementGuid>65d1d3a5-1385-44e6-af13-6922120753fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a362765-9b40-47fd-ab91-7095d03a82d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FoodAndBeverages_modalInput__alPGj </value>
      <webElementGuid>32172f59-dadf-4a22-860f-cf2afa15cab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Gourmet Sandwich Platter</value>
      <webElementGuid>b7fee996-74b1-44fe-bcaa-b97dbfc04902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9a50283-d819-4c1d-b86b-3dcc805e521a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-item-name&quot;)</value>
      <webElementGuid>50fe4360-51de-4c30-8d24-416e5a912e8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new-item-name']</value>
      <webElementGuid>2665055e-3c22-4db7-bd1f-30aa50d2de83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>71ac8ab0-4ce4-4aa1-a89f-e30a2bdaa138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>badc1942-fa2f-4dca-be49-d63498947046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'new-item-name' and @type = 'text' and @placeholder = 'e.g. Gourmet Sandwich Platter']</value>
      <webElementGuid>7f082a7e-c108-4089-a488-fd7e835aa548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
