<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_itemDescription</name>
   <tag></tag>
   <elementGuidId>90a83635-1869-42c4-9047-d6d28d3218b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new-item-desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='new-item-desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4727f809-4b90-4750-a5d7-48907cd716e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-item-desc</value>
      <webElementGuid>76d17492-c691-457f-87b4-8f30536a7cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FoodAndBeverages_modalTextarea__5xina</value>
      <webElementGuid>5a37e80e-70c6-43a5-93ab-3cefd39ded95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Short description</value>
      <webElementGuid>b9ede7b3-bce3-430e-b79b-7c35917ddf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a590fdb0-f73f-4b09-b6ed-effc13394acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f4e6807c-b64b-4ae5-b0dd-50e3590bc766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>new-item-desc-count</value>
      <webElementGuid>fa1a751f-06c6-475b-b82e-635886357208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-item-desc&quot;)</value>
      <webElementGuid>dba55f10-fdda-4750-8573-2a70f6e97cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='new-item-desc']</value>
      <webElementGuid>61e8c9a8-277c-4493-b2aa-7bb7ff31af04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>c86e4f55-4c34-4a15-9f3e-f46f25e5b4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>704c1519-513b-40ca-af83-af16cb44bf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'new-item-desc' and @placeholder = 'Short description']</value>
      <webElementGuid>50d7cb14-263d-4260-9f7f-30fa8906b376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
