<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tands_Next</name>
   <tag></tag>
   <elementGuidId>803a2530-54af-483f-a42a-1f1881f8e529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.TermsAndSettings_btnPrimary__mc4cx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0f7afda-b6b5-42d4-83f2-3e6b1642b36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd8cc60b-8c4b-4385-8d1b-f50b8564abce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TermsAndSettings_btnPrimary__mc4cx</value>
      <webElementGuid>dc05e498-a82a-4ee2-b1dd-44402a45ff5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>5b7386c4-e673-4203-9170-47d9c769e0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>bb829c28-65f7-411e-b312-6c4a8524a083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;TermsAndSettings_termsAndSettingsWrap__kbs7c&quot;]/div[@class=&quot;TermsAndSettings_container__nWMEh&quot;]/main[@class=&quot;TermsAndSettings_mainContent__kRAEp&quot;]/div[@class=&quot;TermsAndSettings_mainInner__y5WbZ&quot;]/div[@class=&quot;TermsAndSettings_actionButtons__Q3-ey&quot;]/div[@class=&quot;TermsAndSettings_rightButtons__UZixn&quot;]/button[@class=&quot;TermsAndSettings_btnPrimary__mc4cx&quot;]</value>
      <webElementGuid>db86ec95-74eb-4bc1-b477-aa3bb84cf10f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[38]</value>
      <webElementGuid>99ef350a-12dd-4e26-9b4a-54e00314176f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div/button[2]</value>
      <webElementGuid>2242889b-321a-41ac-b552-d930cae87bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/following::button[1]</value>
      <webElementGuid>b4de3cdf-aff8-47f9-841d-03d61626db7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/following::button[2]</value>
      <webElementGuid>c037d698-1bd9-46b2-ba44-5674682b40c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>cf614929-5990-4370-aa7f-631f00af32cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>7837e14a-b8c1-4cfb-a941-bed4ce76b952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>9841e6c9-b9f4-4864-b1f3-06d241d7aa22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
