<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tands_Cancellation</name>
   <tag></tag>
   <elementGuidId>54b47b90-de76-4a53-81fa-0c60b6bb962f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[contains(@class, 'sectionCancellation')]//button[contains(@class, 'toggleSwitch')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34c5f420-575b-4a23-a6c5-d57b2ecd0e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64785537-31a8-4b1b-9368-44c09006105e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TermsAndSettings_toggleSwitch__RFxi+ </value>
      <webElementGuid>0a3ac209-e129-4a87-8086-bc84534a33c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>67c1947e-6c03-4ad9-a0f2-5c6da4732b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c09353aa-856f-445d-b51f-e7d23d4e606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;TermsAndSettings_termsAndSettingsWrap__kbs7c&quot;]/div[@class=&quot;TermsAndSettings_container__nWMEh&quot;]/main[@class=&quot;TermsAndSettings_mainContent__kRAEp&quot;]/div[@class=&quot;TermsAndSettings_mainInner__y5WbZ&quot;]/section[@class=&quot;TermsAndSettings_section__wJ9bq TermsAndSettings_sectionCancellation__Apbx5&quot;]/div[@class=&quot;TermsAndSettings_sectionBody__eGFJ4&quot;]/div[@class=&quot;TermsAndSettings_toggleRow__o1qab&quot;]/button[@class=&quot;TermsAndSettings_toggleSwitch__RFxi+&quot;]</value>
      <webElementGuid>e45dca6c-5ebb-479b-9453-80e8f6a41028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[27]</value>
      <webElementGuid>eb0c86df-b76f-404f-8b44-bc532829763d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/section[2]/div[2]/div/button</value>
      <webElementGuid>ac88fb44-ad50-473e-bcdd-5754b6aa1c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable participants to cancel their own tickets'])[1]/following::button[1]</value>
      <webElementGuid>a954ce91-797a-4123-aa5c-39a07adc8c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow User Cancellations'])[1]/following::button[1]</value>
      <webElementGuid>467042a2-84b9-40d8-a8db-78d55f9ea2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disclaimers &amp; Participation Rules'])[1]/preceding::button[1]</value>
      <webElementGuid>196c6015-683c-4cea-92e8-f10d389274f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/div/button</value>
      <webElementGuid>c433c28d-9ba9-466d-aabd-54060c18998c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>85371c4e-1a64-4f34-ace8-00ab37474998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
