<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Zelle_PaymentMethods_toggle</name>
   <tag></tag>
   <elementGuidId>a11b6f95-5758-4d7f-a9a8-1c49c6b87a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(), 'Zelle')]/ancestor::div[contains(@class, 'paymentCard')]//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e742dcb7-4a55-421c-8d66-8c74d64c38b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>236bb2b6-8f9a-49c7-96a5-ab73bf4b2fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PaymentMethods_toggle__f0zMJ </value>
      <webElementGuid>701ea4fb-8555-4769-a014-b4e3191473bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle Zelle</value>
      <webElementGuid>4808c729-e665-47c5-ba89-437a1f4dc00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9204e1c-cba8-49a9-b3a4-3d542986f7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd7e2ae5-aea8-47bb-b281-af4d27e5a383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;PaymentMethods_paymentMethodsWrap__zXTem&quot;]/div[@class=&quot;PaymentMethods_inner__m2l1T&quot;]/div[@class=&quot;PaymentMethods_mainCard__AVJ4y&quot;]/div[@class=&quot;PaymentMethods_mainInner__5x4ne&quot;]/div[@class=&quot;PaymentMethods_paymentMethodsSection__zvbYF&quot;]/div[@class=&quot;PaymentMethods_paymentGrid__Cg8I8&quot;]/div[@class=&quot;PaymentMethods_paymentCard__TUUcl&quot;]/div[@class=&quot;PaymentMethods_paymentCardContent__9xY6l&quot;]/button[@class=&quot;PaymentMethods_toggle__f0zMJ&quot;]</value>
      <webElementGuid>e5b8e228-3c77-4233-bbe0-2288b4ea5d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[18]</value>
      <webElementGuid>653cf5f0-25e3-49c5-82e7-86d64e149b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[3]/div/div[4]/div/button</value>
      <webElementGuid>57dc87bd-3ebe-47ba-ad0c-ac94aaa119f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zelle'])[1]/following::button[1]</value>
      <webElementGuid>ce6c16b6-4659-4389-9c67-6123475930ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venmo'])[1]/following::button[2]</value>
      <webElementGuid>6fc873af-055b-458b-82cb-b779fe992da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash (Offline)'])[1]/preceding::button[1]</value>
      <webElementGuid>17853d52-adcd-44c9-91f0-23f70da5a84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Payment Method'])[1]/preceding::button[2]</value>
      <webElementGuid>294123f0-c42c-4c1f-84d9-32400cbb34f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>bcd885dc-6b41-41f0-803d-8a151a644038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>8944b1be-621f-4999-ad00-f85d76339629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
