<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reg_start_time</name>
   <tag></tag>
   <elementGuidId>813fc6d4-8fbc-41a6-b12d-5513d455aea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.TimePickerInput_timePickerTrigger__0PVW9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[57]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb6f2bd5-d258-42ac-8a3f-a2e392d28f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2d670d5-ad1d-4150-bd03-fbb0c315328e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TimePickerInput_timePickerTrigger__0PVW9</value>
      <webElementGuid>342f1ee5-9768-4b5b-946c-628cb8a6a783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>da1f6283-2930-433f-8481-671c9fac6fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a15b1684-6e14-406d-81e9-a7f4102d363f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--:--</value>
      <webElementGuid>db1f6b90-0ba8-432f-b60f-aa3da8c52f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-free&quot;)/div[@class=&quot;TicketAndPricing_freeGrid__pvN75&quot;]/div[1]/div[@class=&quot;TicketAndPricing_configCard__JqdHE&quot;]/div[@class=&quot;TicketAndPricing_columnsTight__WdxkS&quot;]/div[@class=&quot;TicketAndPricing_columnTight__dY59T&quot;]/div[@class=&quot;TicketAndPricing_inputWithIcon__dzyzw&quot;]/div[@class=&quot;TimePickerInput_timePickerWrap__leACh TicketAndPricing_regTimePicker__b6liV&quot;]/button[@class=&quot;TimePickerInput_timePickerTrigger__0PVW9&quot;]</value>
      <webElementGuid>74288314-9fd3-4af0-9abe-4ddd29ced679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[57]</value>
      <webElementGuid>9f94f71b-2774-4842-9c8b-73749d3fce41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-free']/div/div/div/div[4]/div/div/div[2]/button</value>
      <webElementGuid>1bb9c2da-e164-47e6-b9f9-588ba482b9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[36]</value>
      <webElementGuid>6544b8e9-9ccd-435a-9064-9afc5d1b5978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[36]</value>
      <webElementGuid>f3107640-24e4-43b2-8302-7911f214af3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>af9247ed-52b0-4cc9-991f-4f743c2965b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '--:--' or . = '--:--')]</value>
      <webElementGuid>a2f07918-4cfc-4ad0-8716-393decdbb09d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
