<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reg_end_time</name>
   <tag></tag>
   <elementGuidId>eb9c1458-0f7f-4e9d-bdcc-6d81a0d6ef8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[98]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bea68954-4b91-4d6d-a1a3-6b2ba61ee7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a650281-5d48-4f38-8d31-2a2ea1783ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TimePickerInput_timePickerTrigger__0PVW9</value>
      <webElementGuid>3fd5510f-f40f-4964-9198-64a98ac0163a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>35ca5cdc-5286-4b76-9987-3fb9b1ec86d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2535d059-ba21-47ff-8fec-fc1ab330c2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--:--</value>
      <webElementGuid>e91cde8f-65b9-46eb-81a7-544276fd1200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-free&quot;)/div[@class=&quot;TicketAndPricing_freeGrid__pvN75&quot;]/div[1]/div[@class=&quot;TicketAndPricing_configCard__JqdHE&quot;]/div[@class=&quot;TicketAndPricing_columnsTight__WdxkS&quot;]/div[@class=&quot;TicketAndPricing_columnTight__dY59T&quot;]/div[@class=&quot;TicketAndPricing_inputWithIcon__dzyzw&quot;]/div[@class=&quot;TimePickerInput_timePickerWrap__leACh TicketAndPricing_regTimePicker__b6liV&quot;]/button[@class=&quot;TimePickerInput_timePickerTrigger__0PVW9&quot;]</value>
      <webElementGuid>e7c55c6e-7148-4167-b291-c6e6761768a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[98]</value>
      <webElementGuid>49f97da6-349a-4361-9237-7289aadee319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-free']/div/div/div/div[4]/div[2]/div/div[2]/button</value>
      <webElementGuid>5ecd3215-86f9-4265-b682-621314817403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::button[36]</value>
      <webElementGuid>2f7a26c7-313d-4013-959b-6f061814bb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[2]/following::button[36]</value>
      <webElementGuid>a7821b93-f70b-4069-8b9b-9d1285524440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Visibility'])[1]/preceding::button[1]</value>
      <webElementGuid>1b1575fb-4194-41d6-bdb6-4c53739d90bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>af05a196-c34b-486e-bf4a-026f4efcaabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '--:--' or . = '--:--')]</value>
      <webElementGuid>7d545875-08b5-481d-bfc7-651f8db8bc15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
