<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Free Event</name>
   <tag></tag>
   <elementGuidId>e3b77e4d-f4cf-4a23-97cf-44adc94f7fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-free</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-free']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe17c1d8-6fe1-4952-bb1a-4591ef046ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8d05627-4f6c-495d-82e3-b88c686b3bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-free</value>
      <webElementGuid>6a6ffdb8-2004-4c25-a2eb-76490dd2fc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1f5e41ae-731c-4b68-88c2-412291d39d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83dcec3a-4b84-46da-9169-13c6ce949f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>panel-free</value>
      <webElementGuid>36997b74-a968-4f6b-ab66-2e863b274d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_optionCard__ocoCc</value>
      <webElementGuid>a2cf6de6-8fa3-4ac0-9120-4a9927df6635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Free EventNo charge for attendees</value>
      <webElementGuid>92a757c4-6db3-4de9-861e-9f6bbbc5df54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-free&quot;)</value>
      <webElementGuid>e3f82256-4d74-408b-b10d-24d5496cbc88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tab-free']</value>
      <webElementGuid>c537aeda-0fb2-4c20-9404-807ad6a94524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/section/div[2]/button</value>
      <webElementGuid>5dd9cad6-9d5f-4cc1-9d4e-d1594bb863b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Ticket Type'])[1]/following::button[1]</value>
      <webElementGuid>9ac7ad48-25c9-400e-98e6-708fd20406b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticketing &amp; Pricing'])[1]/following::button[1]</value>
      <webElementGuid>1534345c-e3f8-44a4-98ce-8309b95a7651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8118d214-5e53-48fe-a921-3fb46a2c0a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'tab-free' and (text() = 'Free EventNo charge for attendees' or . = 'Free EventNo charge for attendees')]</value>
      <webElementGuid>961b43f3-b019-47ea-9551-bc46b51faca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
