<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_paymentMethod_Next</name>
   <tag></tag>
   <elementGuidId>bc18172f-7d8c-4027-a89d-d31d3d73ac5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.PaymentMethods_primaryButton__U89Cv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6207db76-9e06-44bc-89d8-832fb68eb2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8444ebaf-6050-4d5a-a57d-dea85fff4798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PaymentMethods_primaryButton__U89Cv</value>
      <webElementGuid>628334c4-7549-4497-aa8d-0571a57c3267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next step</value>
      <webElementGuid>cb59bf84-b36a-4657-a81d-7023d1775a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>ddbe6b9d-a882-47c0-af82-3989216ca4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;PaymentMethods_paymentMethodsWrap__zXTem&quot;]/div[@class=&quot;PaymentMethods_inner__m2l1T&quot;]/div[@class=&quot;PaymentMethods_mainCard__AVJ4y&quot;]/div[@class=&quot;PaymentMethods_mainInner__5x4ne&quot;]/div[@class=&quot;PaymentMethods_formFooter__J-VLy&quot;]/div[@class=&quot;PaymentMethods_footerActions__ftUqI&quot;]/button[@class=&quot;PaymentMethods_primaryButton__U89Cv&quot;]</value>
      <webElementGuid>3e6e08ad-47ba-4f44-8ab1-c0d078f77a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>89cd912a-1526-4a34-b95d-8025f656565d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[5]/div/button[2]</value>
      <webElementGuid>98ff467a-33fe-46cb-8e00-a4bf8ba3b8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/following::button[1]</value>
      <webElementGuid>652d027f-df5f-4839-abe4-b3e87c29d532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/following::button[2]</value>
      <webElementGuid>95e0691f-53c5-4204-b83b-e7152aeecbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>a7ca0643-2236-4eb9-9a67-4e18a6bbb3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>2579bd4d-6870-43df-8fa4-c64d82ade2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
