<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Tickets Available</name>
   <tag></tag>
   <elementGuidId>ae2087f9-c947-436e-9d05-a19aef252ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#freeTotalTickets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='freeTotalTickets']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07b6c6e0-8516-424d-b5c5-1d2ae1d3be91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>freeTotalTickets</value>
      <webElementGuid>f3f3ebdd-32e4-4976-94d4-b765547e2277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TicketAndPricing_input__Oisej</value>
      <webElementGuid>db8b1cb0-d23d-46bc-a19c-bed5eceea594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>50a99ec0-7560-41d4-a7ae-37446f52267e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0337da63-0134-4d23-bc6c-df09f4eadb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>616383d1-cdce-4e69-9065-51066353354c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fd48b4c1-a548-4c00-acae-040802afa278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;freeTotalTickets&quot;)</value>
      <webElementGuid>fcfa9da2-f39c-4e70-b5e6-eb50e987ceb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='freeTotalTickets']</value>
      <webElementGuid>5288c4aa-84e8-4ba2-b356-d6ac0468d1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-free']/div/div/div/div[3]/div/input</value>
      <webElementGuid>28a37828-536e-4db6-a1f3-a46abfcb9ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>eed49ee6-cf72-4f93-b00b-918a1f7789b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'freeTotalTickets' and @type = 'number']</value>
      <webElementGuid>bbffbb16-1f59-4e0a-b36a-ad1aa7eb7fd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
