<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__zelleEmail</name>
   <tag></tag>
   <elementGuidId>7b735eae-bad3-45c2-8702-da42f0142d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zelleEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zelleEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b802e14-99da-468b-8142-5504864c7fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zelleEmail</value>
      <webElementGuid>45fd9712-8506-44be-bd0f-5eb781a400f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7891eb26-2765-46d0-a200-0d45f6e29438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PaymentMethods_input__RgUT7</value>
      <webElementGuid>a934cddf-d80c-4a4b-bedd-dd143e632613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email@example.com</value>
      <webElementGuid>ea207263-5e41-4199-a050-f52955575504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>038fb111-b1c3-4177-9f98-9efd8dd40c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8424c250-2253-4eaa-a4a6-3348640d036b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zelleEmail&quot;)</value>
      <webElementGuid>7b9fb3d1-d9d9-44ff-8e0b-6a23bff056d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zelleEmail']</value>
      <webElementGuid>0d47aaed-a755-4e18-837b-e135b8b77901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>a937bd51-6ada-405b-b7e8-e25b8d028b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a8e8435f-2bca-4df3-a95a-2dfb35ec4e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zelleEmail' and @type = 'email' and @placeholder = 'email@example.com']</value>
      <webElementGuid>83a98bd3-80e1-4640-bbbb-8be2067b213f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
