<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_next_month</name>
   <tag></tag>
   <elementGuidId>48a20003-22b0-49db-9cc5-187bc7580cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class, 'react-calendar__navigation__next-button')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>20838514-5221-45aa-b6f7-40ba1142f1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1775726930952</value>
      <webElementGuid>d2c4ae1d-2051-4f62-8c79-a62876bc0ed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
