<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calendar_day</name>
   <tag></tag>
   <elementGuidId>7770fad9-4585-47ef-9e33-ec2944e5306e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class, 'react-calendar__tile')]/abbr[text()='${day}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>72bc3db3-4d2c-4b6f-97f0-bf3a5d0f13a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1775726971394</value>
      <webElementGuid>9f1395a2-31da-4673-bdce-f23b9434daba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
