<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirmPassword_button</name>
   <tag></tag>
   <elementGuidId>4a409154-e778-40a6-b0b7-7d1595ada5c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resetPassword_continuebtn__GcvcA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='resetPassword_continuebtn__GcvcA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b78164d-2e44-4a01-9051-f501cdaf620b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b9f4c64e-9266-43ae-b1f0-f01ef1321456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resetPassword_continuebtn__GcvcA</value>
      <webElementGuid>0772f717-e5a3-46b6-8b64-74c6037d5223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reset Password</value>
      <webElementGuid>d454002e-1776-4a67-9b97-7f4912fe27d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetPassword_continuebtn__GcvcA&quot;)</value>
      <webElementGuid>bec0428f-acde-4861-8c33-63353bca4e65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='resetPassword_continuebtn__GcvcA']</value>
      <webElementGuid>1f827cae-50c1-4548-9907-ad654273fb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/input</value>
      <webElementGuid>564fea7f-2917-4a2b-b91c-f0ec09ac2563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>a27e3be9-7702-4a60-a2df-bb1ebe1f32cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'resetPassword_continuebtn__GcvcA']</value>
      <webElementGuid>9ed46910-71bc-4154-bfbc-3f910d2dcc00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
