<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgetPassword_button</name>
   <tag></tag>
   <elementGuidId>42b46d68-7a30-47c5-810e-3a380e1acbe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgetPassword_continuebtn__6KzrU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forgetPassword_continuebtn__6KzrU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1535b71-54f8-4b67-9d22-a55df41fbda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9d23c790-cfa6-4bba-9c35-a88a283ad69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgetPassword_continuebtn__6KzrU</value>
      <webElementGuid>d36f78cb-0272-4486-9f2c-e855602d55d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Forgot Password</value>
      <webElementGuid>5d404492-4d85-405e-95a0-81406d98ec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgetPassword_continuebtn__6KzrU&quot;)</value>
      <webElementGuid>f0ad3a33-8d99-4f2c-8e2b-3589b4b6a410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forgetPassword_continuebtn__6KzrU']</value>
      <webElementGuid>e2a0fbd4-8b6f-43a6-a199-782983c18880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/input</value>
      <webElementGuid>61fe0fbd-2896-4ec5-8ca5-eeb0183d9046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>cbd08643-4400-4bac-881f-f9ecdb7c0012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'forgetPassword_continuebtn__6KzrU']</value>
      <webElementGuid>af4bd466-66da-41f7-86cc-6765f3cbdd3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
