<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyOtp_button</name>
   <tag></tag>
   <elementGuidId>74f002e7-d869-4129-95ac-755079eef2c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otpVerify_loginbtn__wOnJC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otpVerify_loginbtn__wOnJC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe12c3a-2b45-4beb-a863-7b22d13d5f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f0bfb39d-f8e9-40a6-88e8-b85fe2fcb640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otpVerify_loginbtn__wOnJC</value>
      <webElementGuid>993940ba-5980-47ed-b651-98cc8ccce6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verify Now</value>
      <webElementGuid>77a1cbdd-6d9f-4be7-983e-919371161ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otpVerify_loginbtn__wOnJC&quot;)</value>
      <webElementGuid>f2cb5128-18ed-4735-b302-6cf8afbd5be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otpVerify_loginbtn__wOnJC']</value>
      <webElementGuid>13d60c8d-4a4d-47c7-8a9a-16df557d39cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/input</value>
      <webElementGuid>3378c84e-e5be-4239-b132-e668746bffca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>ef843dc6-a1f4-4721-a7f7-d41b23f9dfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'otpVerify_loginbtn__wOnJC']</value>
      <webElementGuid>0ecb2845-0a69-48c7-8a88-104e61d0955a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
