<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Vendor_addVendor</name>
   <tag></tag>
   <elementGuidId>cd0602cc-8726-4dc2-89ae-e8a9c7a49b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.AddVendors_btnAddVendor__vXwC5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Add Vendor' or . = 'Add Vendor')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7c18884-6c96-497a-b233-74f579ae59f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96b39785-62a1-4878-aa42-26dc9d1dac49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddVendors_btnAddVendor__vXwC5</value>
      <webElementGuid>15216788-7b5a-45f6-adce-84a0a583c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add vendor</value>
      <webElementGuid>dc8fdf82-519b-4d11-9304-68ad7b24fdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add Vendor</value>
      <webElementGuid>904e5ead-81bd-418d-9aba-29920d50dca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;AddVendors_addVendorsWrap__KIT--&quot;]/div[@class=&quot;AddVendors_container__eLgdD&quot;]/main[@class=&quot;AddVendors_mainContent__br3r8&quot;]/div[@class=&quot;AddVendors_contentCard__Vtlvd&quot;]/div[@class=&quot;AddVendors_vendorSection__c985A&quot;]/div[@class=&quot;AddVendors_vendorSectionHead__7frI8&quot;]/button[@class=&quot;AddVendors_btnAddVendor__vXwC5&quot;]</value>
      <webElementGuid>62e296d2-152a-457e-80ad-eb0f24c9b714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>b6cfcc7b-2a79-44e3-8275-497e70b9b68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[3]/div/button</value>
      <webElementGuid>022339ec-5737-4c07-b12a-94eddc5a1ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor'])[1]/following::button[1]</value>
      <webElementGuid>6ea18d61-058d-4db5-80a1-205a59606285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendors'])[2]/following::button[1]</value>
      <webElementGuid>085fa08d-7b41-4604-ad46-ffc1fab17552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Vendor']/parent::*</value>
      <webElementGuid>a7f11591-3891-4f18-bce9-0cc90a34659d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>c1c13bfe-f27b-400c-ab05-91e018bba777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+Add Vendor' or . = '+Add Vendor')]</value>
      <webElementGuid>aad25d67-98f8-420c-b520-f0fcd1459da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
