<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EventBasics_tokenPurchaseAmount</name>
   <tag></tag>
   <elementGuidId>ecefca3f-711a-4648-8ff5-8aa1387481ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tokenPurchaseAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tokenPurchaseAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55096770-707a-4337-80fd-6ab3938929c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tokenPurchaseAmount</value>
      <webElementGuid>cadc2070-bf1d-4268-bab9-0e293675866b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>87327f52-47b4-4573-94ff-64d990411062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa5a584a-919f-4d88-8749-8606f7a66015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>8df349a5-7a5b-42eb-a269-e138ab500da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventBasics_input__Fa8bB </value>
      <webElementGuid>110a085c-3ceb-4366-bde8-40ee2a41785b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>2e81e44e-e7b5-4b18-a312-89897ad3883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08f23d99-8a56-4548-bbd4-2e041f38b184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Token purchase amount per token in USD</value>
      <webElementGuid>ab8668d0-81d1-4f6e-909e-35498427dcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tokenPurchaseAmount&quot;)</value>
      <webElementGuid>40a1a5b4-3ef7-4b9f-be9b-d56b1d0ca742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tokenPurchaseAmount']</value>
      <webElementGuid>90697e02-728d-49bf-a2fe-9ed1c1e347ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/form/div[3]/div/div/input</value>
      <webElementGuid>0fd3720c-a8db-416e-a73d-ebb6d61cdd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>e8db05aa-2dea-489f-9d05-3d4462184681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tokenPurchaseAmount' and @type = 'number' and @placeholder = '0.00']</value>
      <webElementGuid>63ac21c2-e6d1-4825-8ff6-aa5e57d6c7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
