<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EventBasics_minNumberofTokens</name>
   <tag></tag>
   <elementGuidId>8ebb27ea-777c-40ad-bd8a-6280a3c72ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minimumNumberOfTokens</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='minimumNumberOfTokens']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d00efc5d-cd39-429c-bd76-3a2dd8302641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minimumNumberOfTokens</value>
      <webElementGuid>53d4a87b-28d7-4249-8647-ba49c934925e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0edc2908-0b9c-4a9d-be84-1be8bce8f543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c4295ed3-acc8-4a3c-b8e2-c3f2f3e75de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6359419b-d9f7-4150-9df2-98bfa0643044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventBasics_input__Fa8bB </value>
      <webElementGuid>e809d682-6561-410c-8128-5609fa3d8189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ade4a552-23f5-4da2-843f-475d2c45b860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ffe681b-836f-4196-9e24-7949016b2862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minimumNumberOfTokens&quot;)</value>
      <webElementGuid>a3cd1d3d-ff46-4edc-bd12-8f7afa3c4d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='minimumNumberOfTokens']</value>
      <webElementGuid>0300bd80-1bbb-438f-9307-29de484fc67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/form/div[3]/div[2]/input</value>
      <webElementGuid>f0e6849a-c804-4c4b-a98e-f1b16ef1479b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>517e2440-e1a3-470d-a7e2-452e635df9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'minimumNumberOfTokens' and @type = 'number' and @placeholder = '1']</value>
      <webElementGuid>3889336b-8700-4a40-97b0-e807a12f611e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
