<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RegistrationForm_email</name>
   <tag></tag>
   <elementGuidId>7f87079c-473d-419a-ae14-c64b3a48e054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = 'EmailEmail validation' or . = 'EmailEmail validation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3d61b7b-441b-48c8-96b7-86bed59676f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormBuilder_fieldCard__qbV7i</value>
      <webElementGuid>c1646cff-eb78-4ff0-a341-cb7a07058ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40dbf644-435e-40b6-83ae-c5acd1c95f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EmailEmail validation</value>
      <webElementGuid>d5507476-021e-4a72-8506-1d73e3e44cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;FormBuilder_formBuilderWrapper__rgNB9&quot;]/div[@class=&quot;FormBuilder_mainContainer__kaeqX&quot;]/div[@class=&quot;FormBuilder_sectionContainer__TQK2F&quot;]/div[@class=&quot;FormBuilder_leftSidebar__SOAQr&quot;]/div[@class=&quot;FormBuilder_leftSidebarInner__516oO&quot;]/div[@class=&quot;FormBuilder_elementsContent__qZhVY&quot;]/div[@class=&quot;FormBuilder_elementSection__nPQFv&quot;]/div[@class=&quot;FormBuilder_fieldList__A4WRD&quot;]/div[@class=&quot;FormBuilder_fieldCard__qbV7i&quot;]</value>
      <webElementGuid>1580bade-ee42-4d88-8024-dd9f2abe34f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>20b3f64e-5b38-49e2-a3fc-e6b42438e290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi-line textarea'])[1]/following::div[1]</value>
      <webElementGuid>adcd47a1-3dae-4460-9e5e-e181ce5e247c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Text'])[1]/following::div[2]</value>
      <webElementGuid>e0eb18ae-56c1-488f-a7e4-37d7231c2f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>60372e3b-9202-4c1d-a315-b70a66324b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EmailEmail validation' or . = 'EmailEmail validation')]</value>
      <webElementGuid>91a1a708-c6c6-4da5-b60b-512d3c3453bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
