<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RegistrationForm_shortText</name>
   <tag></tag>
   <elementGuidId>e9e7a433-e74f-43f8-8d18-ebf801d8d009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.FormBuilder_fieldCard__qbV7i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = 'Short TextSingle line input' or . = 'Short TextSingle line input')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20dbb1d9-2343-45d4-92c0-56cd6e1e5670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormBuilder_fieldCard__qbV7i</value>
      <webElementGuid>240658a7-04f9-435e-94f1-4b09096def7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1c93a93-624a-428a-85df-0a13be9a3498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Short TextSingle line input</value>
      <webElementGuid>ed7f901a-2157-45f9-9213-bd458dd16989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_cont2__ylJGe&quot;]/div[@class=&quot;FormBuilder_formBuilderWrapper__rgNB9&quot;]/div[@class=&quot;FormBuilder_mainContainer__kaeqX&quot;]/div[@class=&quot;FormBuilder_sectionContainer__TQK2F&quot;]/div[@class=&quot;FormBuilder_leftSidebar__SOAQr&quot;]/div[@class=&quot;FormBuilder_leftSidebarInner__516oO&quot;]/div[@class=&quot;FormBuilder_elementsContent__qZhVY&quot;]/div[@class=&quot;FormBuilder_elementSection__nPQFv&quot;]/div[@class=&quot;FormBuilder_fieldList__A4WRD&quot;]/div[@class=&quot;FormBuilder_fieldCard__qbV7i&quot;]</value>
      <webElementGuid>bfaaba77-96a3-4b5b-b871-d0df3534c534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>f8b780ff-f6aa-4cce-984c-ae4102d8d64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Fields'])[1]/following::div[2]</value>
      <webElementGuid>d7d41679-6f77-4005-a435-b65a653eb603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image'])[1]/following::div[3]</value>
      <webElementGuid>c0e39289-1287-4f5b-a408-5738372a881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>5378c42a-7e97-4e15-88c9-8158bf51025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Short TextSingle line input' or . = 'Short TextSingle line input')]</value>
      <webElementGuid>0eb96786-5af0-4ec4-a775-82f3b1ae9288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
