<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RegistrationForm_phoneNumber</name>
   <tag></tag>
   <elementGuidId>ff3fb2f1-80ed-444f-b5f2-2dce6053176c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = 'PhonePhone number input' or . = 'PhonePhone number input')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02358c2b-17f1-420e-af94-ca9a6ed743ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormBuilder_fieldCard__qbV7i</value>
      <webElementGuid>c6045019-b0e7-4c5a-bc3e-75de8e1af50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c9820ab-28e0-49c2-aa1b-edbc2705ded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PhonePhone number input</value>
      <webElementGuid>c27776f5-b199-440d-8e20-68d974b53a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_cont2__ylJGe&quot;]/div[@class=&quot;FormBuilder_formBuilderWrapper__rgNB9&quot;]/div[@class=&quot;FormBuilder_mainContainer__kaeqX&quot;]/div[@class=&quot;FormBuilder_sectionContainer__TQK2F&quot;]/div[@class=&quot;FormBuilder_leftSidebar__SOAQr&quot;]/div[@class=&quot;FormBuilder_leftSidebarInner__516oO&quot;]/div[@class=&quot;FormBuilder_elementsContent__qZhVY&quot;]/div[@class=&quot;FormBuilder_elementSection__nPQFv&quot;]/div[@class=&quot;FormBuilder_fieldList__A4WRD&quot;]/div[@class=&quot;FormBuilder_fieldCard__qbV7i&quot;]</value>
      <webElementGuid>487f620e-2b6c-4530-b2f4-e25f18eb15a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div[4]</value>
      <webElementGuid>970f2239-ec92-45ef-ae7d-c65613e9f1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email validation'])[1]/following::div[1]</value>
      <webElementGuid>3bff4476-9aad-48df-b4a3-a60914890fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[2]</value>
      <webElementGuid>dbdac632-4c7e-4cfc-a5df-e74a99552e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>0fb41e63-52e0-44e6-b8d2-08500fb460db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PhonePhone number input' or . = 'PhonePhone number input')]</value>
      <webElementGuid>13729234-bd77-47b8-89cd-f142ab8a44b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
