<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RegistrationForm_fieldLabel</name>
   <tag></tag>
   <elementGuidId>0919178e-345e-4f6c-8a90-95f13f4d79f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prop-field-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop-field-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>698d5f7b-522c-4b80-9fef-edcbec42e892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop-field-label</value>
      <webElementGuid>24594eac-8c24-4c5a-9776-e9914914f217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4fcd00d1-dd12-4f1c-87a5-19413259c918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormBuilder_formGroupInput__rKesY</value>
      <webElementGuid>b0b7da94-081c-4c79-a1ed-fa2bc571791d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Field label</value>
      <webElementGuid>24ede931-3494-41af-8fda-47dd3b8a3100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>New short Text field</value>
      <webElementGuid>c7ff1974-6c0a-4fe2-8a1c-12d8f5e79a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop-field-label&quot;)</value>
      <webElementGuid>c929ea71-9b0d-4640-a70c-83b7383086cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop-field-label']</value>
      <webElementGuid>804d2314-0b2b-4354-b13e-830ccffde882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div[3]/div/div[3]/div/input</value>
      <webElementGuid>9a65666d-498c-4b29-a046-e4e7da10b309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/input</value>
      <webElementGuid>4b8256f1-6271-4513-961a-16f579a89c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prop-field-label' and @type = 'text' and @placeholder = 'Field label']</value>
      <webElementGuid>90ad29de-55fc-4854-b20f-c480bbd82ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
