<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RegistrationForm_placeholderText</name>
   <tag></tag>
   <elementGuidId>6cd5dd0a-8828-47e1-90fa-bf388c6a8053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prop-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop-placeholder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>091b675d-4ec1-4ffb-b9f9-710ef6bd0034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop-placeholder</value>
      <webElementGuid>fb76def9-c9ee-4a7c-9edc-84eb4e3252e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>818d2191-5423-4baf-ab68-9818f4895e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormBuilder_formGroupInput__rKesY</value>
      <webElementGuid>d1260489-6b1a-42d0-8800-ac22a0d472e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enter value</value>
      <webElementGuid>298ba582-6c1e-40ca-8649-ab36bb034db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop-placeholder&quot;)</value>
      <webElementGuid>831a976f-2c6d-4d20-afee-6a49e000ca37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop-placeholder']</value>
      <webElementGuid>20e658bc-fcac-4a55-85d5-8023297aedbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div[3]/div/div[3]/div[2]/input</value>
      <webElementGuid>44d34339-b04d-4114-a686-40cae7f5f8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>119cbacd-1301-405f-b9bc-a1cedd287a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prop-placeholder' and @type = 'text']</value>
      <webElementGuid>3b5b96ae-92f4-4d2e-9dfb-2b39d6d64047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
