<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RegistrationForm_required</name>
   <tag></tag>
   <elementGuidId>dc71cb6f-c614-4c44-9bb6-9db8b65ee740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prop-required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop-required']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e28b07e8-f359-4dc6-93ed-9b7c5b6dd710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop-required</value>
      <webElementGuid>628865a7-c57d-41fd-b66e-8916634ce572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e8ff61d-2013-417d-9502-ec4bf1054d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop-required&quot;)</value>
      <webElementGuid>c04d2f23-1eef-45aa-b72a-a8ca3441f191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop-required']</value>
      <webElementGuid>1d24339d-1e56-4fc2-bb2c-28e84ace76ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div[3]/div/div[3]/div[4]/div[2]/label/input</value>
      <webElementGuid>ca1e9b72-e842-4600-babf-fc41c599402d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>f42ddf6c-a0d4-41eb-b01b-5b85e03e0042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prop-required' and @type = 'checkbox']</value>
      <webElementGuid>64954203-168a-43b1-bbbf-d4611ff35480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
