<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BuildSchedule_endTime</name>
   <tag></tag>
   <elementGuidId>6ec64158-c995-4833-b162-61d4736fec76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endTime-0-0 > button.BuildSchedule_input__2QkyX.BuildSchedule_timePickerTrigger__9F3nM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='endTime-0-0']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe96c16c-9255-48bb-9add-8c4ee13a7f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a16b3943-f02d-4b0a-85be-0a9637ee21e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_input__2QkyX BuildSchedule_timePickerTrigger__9F3nM</value>
      <webElementGuid>1c4a78bb-cd53-466c-add7-ced187b4bb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>7dceace6-f533-4ac3-9917-1ccb0aec8e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14957b23-2f5a-474a-b6bb-46e8b1b998b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--:--</value>
      <webElementGuid>80c921b4-de5d-48d2-94e5-5f3bee18f9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endTime-0-0&quot;)/button[@class=&quot;BuildSchedule_input__2QkyX BuildSchedule_timePickerTrigger__9F3nM&quot;]</value>
      <webElementGuid>cfc87144-0d3b-4029-8f34-87dc3453d056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[14]</value>
      <webElementGuid>870d80a4-c04e-49e0-ab72-397beb70a604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='endTime-0-0']/button</value>
      <webElementGuid>144dcea0-8f50-4015-9fe2-cdda5d1387e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::button[1]</value>
      <webElementGuid>4803690d-e2fa-4186-899c-0b13cc950ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>688f8129-5217-4036-94da-e24d909dd10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '--:--' or . = '--:--')]</value>
      <webElementGuid>b5291cba-212e-4406-9007-fb7018658ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
