<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BuildSchedule_Next</name>
   <tag></tag>
   <elementGuidId>22d607d6-42c1-4980-9c99-70cf491512cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.BuildSchedule_nextButton__nQSPp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d61e5b4b-0f29-4ff5-9c32-dfa35d1f2543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd091a44-de09-46b2-b212-1b7a9cff55ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_nextButton__nQSPp</value>
      <webElementGuid>cfaa4433-57da-4ecf-8448-bc9e647be24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>e6feea7b-10d4-40e0-bdcf-658d96b9e97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;BuildSchedule_scheduleWrapper__TqB15&quot;]/div[@class=&quot;BuildSchedule_container__uPBaz&quot;]/main[@class=&quot;BuildSchedule_mainContent__pNyL3&quot;]/div[@class=&quot;BuildSchedule_footerButtons__tR3lx&quot;]/div[@class=&quot;BuildSchedule_rightButtons__iFLSI&quot;]/button[@class=&quot;BuildSchedule_nextButton__nQSPp&quot;]</value>
      <webElementGuid>402b643b-d52d-43dc-8b9c-b55b900562b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>60a0f6b9-9b0c-4a23-872e-8cee5a93a7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div[2]/div/button[2]</value>
      <webElementGuid>3b13a4cf-3e87-4b85-a048-21a43ada6ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/following::button[1]</value>
      <webElementGuid>8023ac02-89aa-47f0-ac58-aef769dea81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/following::button[2]</value>
      <webElementGuid>3ce3b4f7-baac-423b-ac03-5d375b715889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f075d80b-ae88-4bc5-a888-019d7a1eb637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>c5320f4b-b1a3-4660-89be-ebaa48f9ed18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
