<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BuildSchedule_addSession</name>
   <tag></tag>
   <elementGuidId>76f66c9b-f577-4bed-9623-f9c999cc6d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Add Session' or . = 'Add Session')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.BuildSchedule_addSessionButton__7ILst</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>418d4e89-2525-4e1a-955f-eeac5457142d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>782b4f09-210d-4f98-aecb-3bc833c6f337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_addSessionButton__7ILst</value>
      <webElementGuid>cdd7aa20-96d5-4fca-829e-77ec4cb00fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Session</value>
      <webElementGuid>ee3b3491-ccfc-44a9-a513-996a2d8d0d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;BuildSchedule_scheduleWrapper__TqB15&quot;]/div[@class=&quot;BuildSchedule_container__uPBaz&quot;]/main[@class=&quot;BuildSchedule_mainContent__pNyL3&quot;]/div[@class=&quot;BuildSchedule_contentInner__g8YaC&quot;]/div[@class=&quot;BuildSchedule_scheduleContent__NZP6G&quot;]/div[@class=&quot;BuildSchedule_sessionsWrapper__UkYC4&quot;]/div[@class=&quot;BuildSchedule_leftColumn__MCha1&quot;]/div[@class=&quot;BuildSchedule_addSessionWrapper__Vg66Y&quot;]/button[@class=&quot;BuildSchedule_addSessionButton__7ILst&quot;]</value>
      <webElementGuid>3d49c182-b074-4ca6-8b77-dc6ee5cc4de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>8c81e589-08ae-4246-9ee2-7d8aa3464f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>dfd04daa-05fb-412e-8476-b74e40afa298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Day'])[1]/following::button[1]</value>
      <webElementGuid>8b3b6427-261f-4f87-a752-8d5ad9a103e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>814c6ef8-69ac-4bac-8845-370ae95bf78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Session' or . = 'Add Session')]</value>
      <webElementGuid>329e87b7-09da-43f6-aed4-e543b9949b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
