<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BuildSchedule_startTime</name>
   <tag></tag>
   <elementGuidId>1961c619-9a20-4fa6-8e86-1e517f5db755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.BuildSchedule_input__2QkyX.BuildSchedule_timePickerTrigger__9F3nM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='startTime-0-0']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>061c8bea-7004-4e70-b52f-9b33408786c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51eff945-29de-4f31-a9be-9208dc9c9477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_input__2QkyX BuildSchedule_timePickerTrigger__9F3nM</value>
      <webElementGuid>077bcf54-a85c-4bcf-b16c-d56ae656b9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>4610ac46-c6b2-4922-ae9f-a4a3c161d858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>acd5e931-ffc9-4959-94c2-3674e24447df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--:--</value>
      <webElementGuid>83cf3989-04bb-48c0-bcd1-b466546d8b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime-0-0&quot;)/button[@class=&quot;BuildSchedule_input__2QkyX BuildSchedule_timePickerTrigger__9F3nM&quot;]</value>
      <webElementGuid>3db7c5f1-7e1e-4320-bafe-8b3281e623ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>2847e4a3-37a0-434a-8273-33df7669e6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='startTime-0-0']/button</value>
      <webElementGuid>573f1395-9120-4e65-abb8-3262705a6f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::button[1]</value>
      <webElementGuid>89a75b96-24c4-4ce4-b001-591a8fdd60e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div/div/button</value>
      <webElementGuid>debfa10d-81e8-4430-8133-f79e671a4ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '--:--' or . = '--:--')]</value>
      <webElementGuid>603ce589-e124-4cfb-a2c1-0c9c3c19176b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
