<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BuildSchedule_sessionSpeaker</name>
   <tag></tag>
   <elementGuidId>c0a878f3-6912-4835-a8f7-3518e1f7e67e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#speaker-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='speaker-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ad8421f-d244-4f9a-95b6-76963b523168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>speaker-0-0</value>
      <webElementGuid>641319bf-2e21-49df-9797-b01fae6bf692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ed64af9-a66a-47af-b181-2156025b6fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_input__2QkyX</value>
      <webElementGuid>37458fa2-0408-4974-ba62-d503ee51502c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. John Smith</value>
      <webElementGuid>b41f16bc-6ebf-4838-9be7-9398e927edb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>66d4b338-ecf6-42be-ba93-6bbef3c2a613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;speaker-0-0&quot;)</value>
      <webElementGuid>d56ed4d4-08b5-44e3-898a-18f5e0c87ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='speaker-0-0']</value>
      <webElementGuid>387094bf-d0be-408f-9fe1-caab4e74d5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div[2]/div/div/div[2]/div[4]/input</value>
      <webElementGuid>1875121f-652c-40a0-9051-936c3d8bc524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2776948a-a51b-43fd-b200-25ae7aa3dcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'speaker-0-0' and @type = 'text' and @placeholder = 'e.g. John Smith']</value>
      <webElementGuid>e5c6a95c-d48b-49eb-89bf-c7d91146681e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
