<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BuildSchedule_location</name>
   <tag></tag>
   <elementGuidId>95451cbc-d8ca-44c1-86e6-27ec7658bd31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8ef0a0c-ddd8-4e66-ac4d-d28238375623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location-0-0</value>
      <webElementGuid>0252471a-e626-4170-8a1a-422fb4d39c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a00897cb-1030-464d-83ab-8b30540e3b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_input__2QkyX</value>
      <webElementGuid>501f13e5-e1f0-4337-bc67-073627a75da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4dfd2eca-b3e6-4fc0-b91c-5780c4987824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Main Hall</value>
      <webElementGuid>e6ca1102-d1f1-4d52-a6b6-5cbe3b8db101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location-0-0&quot;)</value>
      <webElementGuid>4b302a52-3c94-4149-af58-ef80956ebc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location-0-0']</value>
      <webElementGuid>9c62935f-4d6e-4b1f-bd73-4570a4e73df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>af51ea6d-62bd-4721-a9f1-0a634a61933c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3589e33d-1cc4-434b-bd6e-34a282394edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'location-0-0' and @type = 'text' and @placeholder = 'e.g. Main Hall']</value>
      <webElementGuid>052f8172-d29a-4c7e-ba61-41316636a4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
