<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BuildSchedule_sessionTitle</name>
   <tag></tag>
   <elementGuidId>5b782c4f-f50b-4575-9449-7f9cad6edbab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63e6d910-35d1-49d3-90dc-70a23ac09ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title-0-0</value>
      <webElementGuid>d14a8041-e7f9-41ff-9c91-35efbe53c5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>990f997b-9d2c-4e44-965d-62b71b5e704a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_input__2QkyX</value>
      <webElementGuid>767ac688-b8a3-4013-84d6-9c5ce83f0b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Opening Ceremony</value>
      <webElementGuid>09fc46d1-93a7-4ad3-8cf1-ff679947d293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>c11202b6-7ac4-41b7-9034-f6031b324b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-0-0&quot;)</value>
      <webElementGuid>e58a2cfd-92b9-4dad-a8a7-c149633b5f42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title-0-0']</value>
      <webElementGuid>fc95e076-4f96-4c3a-888b-08ed7903b52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div[2]/div/div/div[2]/div[3]/input</value>
      <webElementGuid>5274178a-ed12-42f1-b08b-0274a2ef50c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>11a097c1-3840-45f6-a56d-61135bcc4ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'title-0-0' and @type = 'text' and @placeholder = 'e.g. Opening Ceremony']</value>
      <webElementGuid>0fd15620-0be3-41bb-bf27-5bc486413cfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
