<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BuildSchedule_streamingLink</name>
   <tag></tag>
   <elementGuidId>97219a2c-62d0-4594-8c12-fb313ac6b84f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#streaming-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streaming-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f25554cc-ae91-404d-b3f1-ba2b20520c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streaming-0-0</value>
      <webElementGuid>4d5461fa-041d-4af2-8f16-8e65358ec12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>64f2fd61-ce71-4f58-9926-b9047969dcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_input__2QkyX</value>
      <webElementGuid>b5f63334-671f-451b-8353-fae36d916980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://...</value>
      <webElementGuid>4f3e418c-72f2-45ff-b6ca-307f398fc755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>7f09c472-3c89-42f9-9ca3-53c7f3679cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streaming-0-0&quot;)</value>
      <webElementGuid>1a85f07b-0458-4169-8597-350c43006d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streaming-0-0']</value>
      <webElementGuid>fccce1e0-fb84-4f20-8e80-b065f52212e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div[2]/div/div/div[2]/div[5]/input</value>
      <webElementGuid>fd646bf9-2587-4be4-8e49-e487609b6533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>b6b9125a-745d-4268-bfe1-2b457903cd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'streaming-0-0' and @type = 'url' and @placeholder = 'https://...']</value>
      <webElementGuid>1c6a7d69-1476-4c21-ae34-0e8ba9566c48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
