<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_BuildSchedule_descriptionNotes</name>
   <tag></tag>
   <elementGuidId>3fe290bf-e73c-431f-9a58-e6f255005457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>544b0546-13ba-4c8e-a1ed-099d127b51e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description-0-0</value>
      <webElementGuid>b3bc045e-9069-4014-892b-029bb6787e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BuildSchedule_textarea__+Bg5+</value>
      <webElementGuid>b323db3b-dc5f-4f77-bf8b-286db527808b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>86242adf-1354-454d-b4f1-293c19bb0894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Welcome guests and kick off the event with an inspiring keynote.</value>
      <webElementGuid>0d3b8be8-3b3c-4be0-bf35-e8b014fc44ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>86d45f33-911d-42ae-b7dd-3ec758cd8dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description-0-0&quot;)</value>
      <webElementGuid>4764078c-2225-4698-96b1-b27da99d1ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description-0-0']</value>
      <webElementGuid>aaaa7dd5-fe62-47ad-991b-0f486dad94da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div[2]/div[2]/div/div/div[2]/div[6]/textarea</value>
      <webElementGuid>630c8dcb-a7a7-43a5-afbc-f19551658af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>64e1603e-06e4-40b1-9bb4-7f655559bf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'description-0-0' and @placeholder = 'Welcome guests and kick off the event with an inspiring keynote.']</value>
      <webElementGuid>233a78ad-b62b-40cd-ae85-c41c738275e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
