<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mediaBranding_social-instagram</name>
   <tag></tag>
   <elementGuidId>d94c485f-55a8-432f-9e36-a21915adb188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#social-instagram</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='social-instagram']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2026c86a-7e4a-4072-bc00-d8e30d61f28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>social-instagram</value>
      <webElementGuid>34d48460-65fe-443b-9bc2-1b7ab556f637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>8e3d2162-b203-4e63-9e6b-a4d656027683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Media_textInput__hrl7r</value>
      <webElementGuid>76a8faaa-5013-4c94-a927-0ac309c7c260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://instagram.com/...</value>
      <webElementGuid>ce55f8ec-8869-4b6e-938a-6724cefb19d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Instagram URL</value>
      <webElementGuid>598514cf-5c79-4802-b5c9-84f71bd38929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94784b54-8f19-49a8-8d45-a01aa7f02f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;social-instagram&quot;)</value>
      <webElementGuid>9a4a9b30-9a59-4821-ab2c-d1a115986f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='social-instagram']</value>
      <webElementGuid>3252b9cc-74a4-4a07-8436-e318e33e48a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/div/div[5]/div[2]/div[2]/input</value>
      <webElementGuid>e16c961c-58ba-4a21-ac36-eb7a7b73981a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>31f5f790-553e-46c2-9d51-915d8e05c914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'social-instagram' and @type = 'url' and @placeholder = 'https://instagram.com/...']</value>
      <webElementGuid>821b2142-c3b4-44e3-973f-9b89985650cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
