<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mediaBranding_social-facebook</name>
   <tag></tag>
   <elementGuidId>3287d5bf-245e-4e0b-bdfa-6ed8ee0cd60c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#social-facebook</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='social-facebook']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec756db7-a75a-4291-88db-42dc52d726b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>social-facebook</value>
      <webElementGuid>d6670e37-b8dc-41fd-ad5c-81deb57ea541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>928e8ce4-824d-4e9e-8cb2-fe322b090b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Media_textInput__hrl7r</value>
      <webElementGuid>d760ae94-a70f-4a6e-9f51-47f0f01d5a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://facebook.com/...</value>
      <webElementGuid>924de8d3-3a8d-4842-8c22-8625761d16a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Facebook URL</value>
      <webElementGuid>bbfd3c09-b3cc-4dcd-a440-5120cdb422eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad57531f-59d5-4eef-92a5-1b78b12faf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;social-facebook&quot;)</value>
      <webElementGuid>0db32f1c-f355-4271-8ae4-e2f7190a8e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='social-facebook']</value>
      <webElementGuid>75872138-5001-41ed-8da6-e41d4935b3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>664e0843-cd27-4393-915e-c3ebd4932390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>de4ed3bb-9eb5-43d1-840c-1f874d2c86eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'social-facebook' and @type = 'url' and @placeholder = 'https://facebook.com/...']</value>
      <webElementGuid>5cf83196-45ac-42b5-ac80-608abd405a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
