<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate Setup</name>
   <tag></tag>
   <elementGuidId>5c28c25b-0de3-434b-9ac7-017c1f779b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Generate Setup' or . = 'Generate Setup')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.AiPrompt_primaryBtn__hDcCV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2135137-0192-40a2-aebe-6eb4d083072e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>999001d5-d875-4074-8e2a-61d9ecab9087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AiPrompt_primaryBtn__hDcCV</value>
      <webElementGuid>aac4bc11-f391-4aaf-add5-3be5d8cb6334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Generate setup with AI</value>
      <webElementGuid>ae321f6d-7106-4654-8cb0-5968e3e04841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>791bae3f-b61c-4f86-a945-d9ded952cf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate Setup</value>
      <webElementGuid>c448083c-b2da-4154-b43b-78cad25efe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;AiPrompt_aiPromptWrapper__fej6G&quot;]/main[@class=&quot;AiPrompt_page__mlz8D&quot;]/div[@class=&quot;AiPrompt_card__sctbu&quot;]/div[@class=&quot;AiPrompt_container__YQqi2&quot;]/div[@class=&quot;AiPrompt_actions__ylEud&quot;]/button[@class=&quot;AiPrompt_primaryBtn__hDcCV&quot;]</value>
      <webElementGuid>1fa629d9-9e03-40ef-a7ba-478f5c835946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>b8868740-15d2-4614-968e-dec9072330b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/div[2]/button</value>
      <webElementGuid>e24021c0-3485-43f0-b6f0-7689a7d0f3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MarQ AI is ready to generate your event setup'])[1]/following::button[1]</value>
      <webElementGuid>0b67f610-8407-405d-85a8-5bbdc274b99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Banner'])[1]/following::button[2]</value>
      <webElementGuid>dd0785ba-5b5c-46f0-ba0f-b23083a0f1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip and Continue Manually'])[1]/preceding::button[1]</value>
      <webElementGuid>38f5e083-3d38-4810-8941-c5ece2ec5015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate Setup']/parent::*</value>
      <webElementGuid>0774cf18-2113-40b8-8896-32c496e32630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>bba736e2-44ce-4bbe-99a0-4e3ee735c473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Generate Setup' or . = 'Generate Setup')]</value>
      <webElementGuid>fa044e69-c4ed-4ee8-9a99-30fe4221f37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
