<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_AI_eventPrompt</name>
   <tag></tag>
   <elementGuidId>2921b6a5-1621-4d51-a13e-ecf7576eb462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventPrompt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='eventPrompt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7307d78d-0c1f-421b-9d33-3294edd8ec0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventPrompt</value>
      <webElementGuid>f9f9a7b3-a99f-4fa4-ae27-f0b46fea596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eventPrompt</value>
      <webElementGuid>1c491673-aa41-4d14-960a-328ef57c1858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: Create a charity run in New York on March 15, 2026, with a free registration, food stalls, and raffle prizes.</value>
      <webElementGuid>5e619a4e-687c-45fb-9458-3031779d460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>prompt-counter</value>
      <webElementGuid>f3e7c2e5-8055-46a5-bcb3-bf702bae5977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Describe your event</value>
      <webElementGuid>59c5bdea-c352-4cfe-b277-744369101456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de32c4a5-2d26-43e8-87af-5e1e98ff44fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AiPrompt_textarea__svPpx</value>
      <webElementGuid>9d8b3113-f3d5-417b-be44-294a657567d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventPrompt&quot;)</value>
      <webElementGuid>d9c3ea2c-bab0-41d5-8bf5-af9dd303b53d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='eventPrompt']</value>
      <webElementGuid>b5a2be7f-167c-4668-999e-93e677ac42d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/section/div/textarea</value>
      <webElementGuid>c1c86220-a7e6-4bff-9911-8f25bd6a3ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>72d068eb-16c5-43e8-b949-ad89d830b529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'eventPrompt' and @name = 'eventPrompt' and @placeholder = 'Example: Create a charity run in New York on March 15, 2026, with a free registration, food stalls, and raffle prizes.']</value>
      <webElementGuid>413d7436-2d28-4797-85de-53433791881b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
