<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Event Basics_Next</name>
   <tag></tag>
   <elementGuidId>f7308e65-b12d-4860-814c-ece5adaf2013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.EventBasics_primaryButton__mUWTU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4373b14d-a5f5-473a-8079-7e8ee7102ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21efdf12-c07a-4e71-bdb2-aacf923779b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventBasics_primaryButton__mUWTU</value>
      <webElementGuid>2f07c91c-0559-4370-ace7-5e5575985f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>410bc29d-bab3-4d95-9280-d07af426093c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;EventBasics_eventBasicsWrapper__grRvO&quot;]/div[@class=&quot;EventBasics_inner__+GSCg&quot;]/main[@class=&quot;EventBasics_main__8GQBe&quot;]/div[@class=&quot;EventBasics_mainInner__dn2Z2&quot;]/form[@class=&quot;EventBasics_form__1gl+i&quot;]/div[@class=&quot;EventBasics_formFooter__LkD9B&quot;]/div[@class=&quot;EventBasics_footerActions__QPtRS&quot;]/button[@class=&quot;EventBasics_primaryButton__mUWTU&quot;]</value>
      <webElementGuid>f37a5bb0-3e87-4241-90ce-06ead39c6a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[23]</value>
      <webElementGuid>f1e785bf-1f1a-46fd-8e54-0589962c0719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/form/div[3]/div/button[2]</value>
      <webElementGuid>af91618b-054f-46ad-b9e6-fca01fe23636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/following::button[1]</value>
      <webElementGuid>980ba64f-dea7-480f-8e14-903d745e3b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/following::button[2]</value>
      <webElementGuid>4d9f8441-708c-4239-ab26-6835da8758f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>e79c615b-9723-41b4-adde-cdbf6c0cbb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>950e0932-f0e3-4b50-bc1c-99985df39ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
