<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Event Basics_startup</name>
   <tag></tag>
   <elementGuidId>2b55194e-261f-401b-a0b4-794f87e762ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.EventBasics_suggestedPill__BmRDM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'startup' or . = 'startup')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc8b70af-d596-4c29-9ddf-3559644ff902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>491a878b-a533-4bf7-86c0-4ad494c85d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventBasics_suggestedPill__BmRDM</value>
      <webElementGuid>363778c7-f3c0-40a9-af3c-bb8dbd376a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>startup</value>
      <webElementGuid>998ab471-46e4-44f8-bcf4-a1b3580e87ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestedTags&quot;)/div[@class=&quot;EventBasics_suggestedTags__MhKj2&quot;]/button[@class=&quot;EventBasics_suggestedPill__BmRDM&quot;]</value>
      <webElementGuid>b4d037b6-69e4-4df4-a269-5590ef71b084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>8c633a93-172a-4f6e-95fd-036cebfb2efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suggestedTags']/div/button</value>
      <webElementGuid>c9b3eb63-6af2-4070-8c17-7eba53943026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggested tags:'])[1]/following::button[1]</value>
      <webElementGuid>e7a03578-416c-4f1a-a7d3-81afd89dd486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/following::button[1]</value>
      <webElementGuid>918b2f5a-4a4b-4903-ba75-aed9a21049dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='innovation'])[1]/preceding::button[1]</value>
      <webElementGuid>3a6a706f-d393-4f00-a5f9-747024b5e2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='community'])[1]/preceding::button[2]</value>
      <webElementGuid>03732e72-43c9-475d-aac1-5af09f134809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='startup']/parent::*</value>
      <webElementGuid>41a739b4-6031-4440-88bc-48423a312236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[3]/div/button</value>
      <webElementGuid>bd4b5b39-d76a-42a6-aeaf-a313e5d9fb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'startup' or . = 'startup')]</value>
      <webElementGuid>fce6f716-6c1c-4084-909b-0191ae464d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
