<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Event Basics_eventName</name>
   <tag></tag>
   <elementGuidId>0cf8dd1f-a443-4fa3-95e7-088e398d498e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eventName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>548aad93-250d-44bd-8cde-df6ff5c7ae3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventName</value>
      <webElementGuid>48ee5897-eae2-4a02-8540-0083be63e310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fffd09d-9e77-4f3f-9fe0-67931c5d5065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventBasics_input__Fa8bB </value>
      <webElementGuid>822eb558-6c8c-4470-9bfb-65bf8e025d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Tech Innovation Summit 2024</value>
      <webElementGuid>dff77ff4-14ae-409b-8cdc-961760c5692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>ddc998bd-cd29-48bc-9af3-aedbdddeb491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>baf07d12-e24c-47f5-b1a1-833312967d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1d2e517-4efa-4d9b-8c2f-0f0eb4fbda20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>eventName-hint</value>
      <webElementGuid>1d9db152-e9d3-4d6e-9d12-c1e10702e22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test Event</value>
      <webElementGuid>b87ebaba-a051-4dc9-8ece-6c0b10470580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventName&quot;)</value>
      <webElementGuid>abbccd9d-0ea6-41c9-925f-2eb1fdb14b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eventName']</value>
      <webElementGuid>486a77ca-ebf4-4acb-a160-6445fc3be919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/form/div/input</value>
      <webElementGuid>dea515d0-f419-49bd-a874-449a6849eacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ef145bdb-cdce-4320-99bf-8c83510bef81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eventName' and @type = 'text' and @placeholder = 'e.g. Tech Innovation Summit 2024']</value>
      <webElementGuid>f1989fe7-71c2-4517-9c03-b701df0fbd2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
