<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateAndLocation_physicalLocation</name>
   <tag></tag>
   <elementGuidId>7b2bafc0-fa2e-4736-bc2d-c0b24c93d2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'text' and @placeholder = 'Start typing address...']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.DateAndLocation_addressInputWrapper__Y6k4d > input.DateAndLocation_textInput__6-rVf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb88ef35-7581-47e8-9b88-b42e45f84635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df8b55c2-d73a-4dbb-9e82-aba38b45421e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DateAndLocation_textInput__6-rVf</value>
      <webElementGuid>6ecd9714-080f-4aef-bb24-20c0217362e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing address...</value>
      <webElementGuid>0d728b91-57dd-448e-9678-ed7719de1d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f4fd8c6-0353-4055-b3a5-4ad11503e2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Address for venue</value>
      <webElementGuid>cb394b7b-8d49-4123-89d9-7d787a337b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;DateAndLocation_dateAndLocationWrapper__eHXvP&quot;]/div[@class=&quot;DateAndLocation_mainContainer__y3K4X&quot;]/div[@class=&quot;DateAndLocation_mainContent__W13na&quot;]/div[@class=&quot;DateAndLocation_contentInner__U49Eb&quot;]/section[@class=&quot;DateAndLocation_section__+zCCJ DateAndLocation_sectionEventLocation__Ucd5u&quot;]/div[@class=&quot;DateAndLocation_eventLocationSection__wKoSM&quot;]/div[@class=&quot;DateAndLocation_venuesSection__xvHIg&quot;]/div[@class=&quot;DateAndLocation_venuesList__casvl&quot;]/div[@class=&quot;DateAndLocation_venueCard__Sxs-2&quot;]/div[@class=&quot;DateAndLocation_venueHeader__zOJlG&quot;]/div[@class=&quot;DateAndLocation_venueInfo__PVPY-&quot;]/div[@class=&quot;DateAndLocation_venueDetails__ecReE&quot;]/div[@class=&quot;DateAndLocation_addressInputWrapper__Y6k4d&quot;]/input[@class=&quot;DateAndLocation_textInput__6-rVf&quot;]</value>
      <webElementGuid>12cced36-69fd-4049-9766-79e707fb9c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>a54ff830-5736-4fcf-9d72-dc96fdcab946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/section[2]/div[3]/div/div[2]/div/div/div/div[3]/div/input</value>
      <webElementGuid>51cdc7d4-e63c-45ac-ad0d-68bba2bd1f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a8a3726f-8c7f-4af3-ada4-2eda0e6a0b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Start typing address...']</value>
      <webElementGuid>59b1a385-3496-4dd7-882a-edb128a61414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
