<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateAndLocation_streamingUrl</name>
   <tag></tag>
   <elementGuidId>ee845fb9-f011-466b-9bfa-9835bea1b555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streamingUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#streamingUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d03e79a8-e6ac-4a5d-a686-327bee6c1a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>7a80d75d-a407-441d-9c64-ec2a16ed1ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streamingUrl</value>
      <webElementGuid>8982f058-9d15-416f-b080-9b75fa8e4f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DateAndLocation_textInput__6-rVf </value>
      <webElementGuid>900d62b6-b855-4da8-837d-3981b4ba5251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://zoom.us/j/123456789</value>
      <webElementGuid>f1bdbbe8-2dca-425f-87a8-227c748ac1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fda6b91e-7d82-4854-8290-26e4b6df4095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streamingUrl&quot;)</value>
      <webElementGuid>bc14c003-a8eb-485c-9769-ac72fc9be6c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streamingUrl']</value>
      <webElementGuid>822bb734-b934-441b-bb9a-d4518e57cf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/section[2]/div[3]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>f35ff06b-3a48-47fa-9155-75d276a2653f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/input</value>
      <webElementGuid>4301d1b7-7441-46c9-b473-931337f256de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'url' and @id = 'streamingUrl' and @placeholder = 'https://zoom.us/j/123456789']</value>
      <webElementGuid>37d8eab4-5690-4ed6-99bd-a4d35f76452d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
