<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateAndLocation_physicalVenue</name>
   <tag></tag>
   <elementGuidId>ef089575-7b83-494b-a954-e13709dbad1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'text' and @placeholder = 'Venue name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.DateAndLocation_textInput__6-rVf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dda2adb-909b-4030-a394-5fe44e2189e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6785f5e7-daf1-449d-8f26-ff5b103ec78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DateAndLocation_textInput__6-rVf</value>
      <webElementGuid>98aa0c48-4d85-4b51-aa38-f7cdc4584924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Venue name</value>
      <webElementGuid>e20da68a-6df2-4e33-8bf3-a5e6a3aa87f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;DateAndLocation_dateAndLocationWrapper__eHXvP&quot;]/div[@class=&quot;DateAndLocation_mainContainer__y3K4X&quot;]/div[@class=&quot;DateAndLocation_mainContent__W13na&quot;]/div[@class=&quot;DateAndLocation_contentInner__U49Eb&quot;]/section[@class=&quot;DateAndLocation_section__+zCCJ DateAndLocation_sectionEventLocation__Ucd5u&quot;]/div[@class=&quot;DateAndLocation_eventLocationSection__wKoSM&quot;]/div[@class=&quot;DateAndLocation_venuesSection__xvHIg&quot;]/div[@class=&quot;DateAndLocation_venuesList__casvl&quot;]/div[@class=&quot;DateAndLocation_venueCard__Sxs-2&quot;]/div[@class=&quot;DateAndLocation_venueHeader__zOJlG&quot;]/div[@class=&quot;DateAndLocation_venueInfo__PVPY-&quot;]/div[@class=&quot;DateAndLocation_venueDetails__ecReE&quot;]/input[@class=&quot;DateAndLocation_textInput__6-rVf&quot;]</value>
      <webElementGuid>1e74aa95-4119-4aca-9f7f-8306559b05f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>883ee4ae-9a02-41e8-b2d8-7b8f03fdf0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/section[2]/div[3]/div/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>9f277811-45b0-4487-9a4b-01d5bdc4bdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7e1a9f76-ec45-4a88-b493-eef80d3a16a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Venue name']</value>
      <webElementGuid>fd7b227d-96b5-4510-8085-46f195527103</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
