<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DateAndLocation_selectPlatform</name>
   <tag></tag>
   <elementGuidId>0c4c8c96-f9c0-48c5-99a0-9270de836dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'platformSelect' and (text() = 'Select a platformZoomGoogle MeetYouTubeMicrosoft TeamsCustom' or . = 'Select a platformZoomGoogle MeetYouTubeMicrosoft TeamsCustom')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#platformSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='platformSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>648e5c6c-06b6-4241-9c6d-21a4c4de0860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>platformSelect</value>
      <webElementGuid>3b87c887-bc6d-4343-a241-1178f27cadbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DateAndLocation_selectInput__GbQR6</value>
      <webElementGuid>ecb261b1-6c28-4885-b6ee-eefd75f26d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a platformZoomGoogle MeetYouTubeMicrosoft TeamsCustom</value>
      <webElementGuid>7c0e54aa-fc42-428c-9310-5a5f0693c100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;platformSelect&quot;)</value>
      <webElementGuid>2b0baf42-eae4-4f26-972d-efa23c5d537a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='platformSelect']</value>
      <webElementGuid>e87fb894-14e9-485e-b8d8-47be951c5c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/section[2]/div[3]/div/div/div[2]/div/div/select</value>
      <webElementGuid>7b94a3ec-d62e-4855-afce-d70fdbbca7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Your Platform'])[1]/following::select[1]</value>
      <webElementGuid>5ee3ef91-c847-4c32-8555-411362899a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Event'])[1]/following::select[1]</value>
      <webElementGuid>3f9210fe-cf87-4815-829a-a89574961e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoom'])[2]/preceding::select[1]</value>
      <webElementGuid>c2f0da30-5cf2-4e74-a941-4d95492c8e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meet'])[1]/preceding::select[1]</value>
      <webElementGuid>2408e525-161a-4665-9448-910297c66d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/select</value>
      <webElementGuid>edf16baf-5f38-4794-9ccc-151b7dc45eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'platformSelect' and (text() = 'Select a platformZoomGoogle MeetYouTubeMicrosoft TeamsCustom' or . = 'Select a platformZoomGoogle MeetYouTubeMicrosoft TeamsCustom')]</value>
      <webElementGuid>cf93539e-e5fa-43ce-9853-356c6b4c8d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
