<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Support Ticket</name>
   <tag></tag>
   <elementGuidId>e6e4d9d9-1325-40ee-ad76-48aedc77555d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[type=&quot;submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc4918fb-75d5-4f29-ad75-1b184d7fbafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e9b860ed-a2be-41ca-aee4-26efb09c1fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Contact_submitButton__k8SYH</value>
      <webElementGuid>35285170-bfd6-4961-801d-715d9d651afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Support Ticket</value>
      <webElementGuid>608ede6f-0310-4b1e-8921-22decdc32e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9079020a2e38f5631afdd3ace81c44b3</value>
      <webElementGuid>d86eedfe-d1db-4223-846f-364a50cc1ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@type = 'submit']</value>
      <webElementGuid>31367341-398c-43a6-9d7d-ea77c6c9d050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@type = 'submit']</value>
      <webElementGuid>d3001803-e6c4-4ce6-b666-af04ce9cafd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Submit Support Ticket' or . = 'Submit Support Ticket')]</value>
      <webElementGuid>e714571d-2d87-40a2-8858-3db1d967885c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
