<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File Attachment</name>
   <tag></tag>
   <elementGuidId>20ca66ed-8a48-43b7-abd2-aa06053f3d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5202be4-6836-4fcc-b292-3c39e5fa2f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file-input</value>
      <webElementGuid>cb70f8f0-d18b-4a4b-8483-fcbae1c371a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Contact_fileInput__uXYGl</value>
      <webElementGuid>fdf24d4b-aa74-44a4-946c-26b02f9329e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d9dc388e-8e7c-4258-b891-7495dee30ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png,.jpg,.jpeg,.pdf</value>
      <webElementGuid>fa54d64f-bee5-4a83-9256-a76c3a7953e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4702d2d2ed34d906aff763da98d104b4</value>
      <webElementGuid>4065f82f-f0b6-4894-9971-5fb6ae8281fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'file-input']</value>
      <webElementGuid>441b7ff5-534e-42df-af0c-b32199319b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'file-input']</value>
      <webElementGuid>4740eeb8-f16c-4734-80a8-9c5296d55ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'file-input' and @type = 'file']</value>
      <webElementGuid>b2e5688f-3887-4506-91d8-8525f23b78ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
