<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_formDescription</name>
   <tag></tag>
   <elementGuidId>f9ae8dfa-796c-43f4-98bb-04732ddb5504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9a829f35-7077-4ae8-bc67-54227f0c2efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>2f151cde-20df-41a2-af01-08b3a8d06153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>bc825462-59a5-4ca0-b4e9-290d504178a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Contact_textarea__gh-oo </value>
      <webElementGuid>fdf75f71-28d1-4948-bb11-e862e9bb3be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please describe your issue in detail. Include any error messages, steps you've taken, and what you expected to happen.</value>
      <webElementGuid>2692f6db-5fdc-40cc-b5ca-40e93cf9f218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>44259472-1043-40a0-a13e-37f26d9fa7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b1c1b906-0527-4b9b-b7f8-c75701453a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f15659857beeba9ef4101df0d8028d15</value>
      <webElementGuid>30121972-35eb-45bc-bcfe-27289e2c018a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'message']</value>
      <webElementGuid>bc4d81f8-2bd5-4d69-a59d-67a5a59cb6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'message']</value>
      <webElementGuid>b13ba912-f25f-431d-8db7-ee1385ffe101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'message' and @name = 'message' and @placeholder = concat(&quot;Please describe your issue in detail. Include any error messages, steps you&quot; , &quot;'&quot; , &quot;ve taken, and what you expected to happen.&quot;)]</value>
      <webElementGuid>e3a9e1ab-91bc-4678-b471-cffa691d3156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
