<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tandn_Next</name>
   <tag></tag>
   <elementGuidId>0ecd7755-a5fc-469e-be70-970cd5a3b374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.TermsAndNotes_nextButton__XZHW8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7df2a347-84b5-4c5e-8798-22a9757ba6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cade1df5-8626-4bb8-9fe0-53348a3e1f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TermsAndNotes_nextButton__XZHW8</value>
      <webElementGuid>8782c7a7-07f5-47f4-8f7b-56caa30ddbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>2d7ffcc0-c023-4305-9cc1-3ba7a8b7bf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>278da823-b2b6-4138-a04e-32bc252c1fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;TermsAndNotes_termsAndNotesWrap__Uoj59&quot;]/div[@class=&quot;TermsAndNotes_container__5siCT&quot;]/main[@class=&quot;TermsAndNotes_mainContent__cZjlt&quot;]/div[@class=&quot;TermsAndNotes_mainInner__41VIJ&quot;]/div[@class=&quot;TermsAndNotes_bottomNav__edGp2&quot;]/div[@class=&quot;TermsAndNotes_rightButtons__qY7tI&quot;]/button[@class=&quot;TermsAndNotes_nextButton__XZHW8&quot;]</value>
      <webElementGuid>16fac807-d7d5-4015-b999-4324123780cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[35]</value>
      <webElementGuid>27633511-12e7-4cc4-a206-1301eb421ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div[2]/div[3]/div/button[2]</value>
      <webElementGuid>386ed8a7-affe-48b8-b7ca-321871c86151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/following::button[1]</value>
      <webElementGuid>928fb094-c846-4fea-8c2c-a818f874738f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/following::button[2]</value>
      <webElementGuid>c13c478f-c335-4ebd-8d08-e752a066c9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>adb95038-6611-4cfc-a5d6-99137c196ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>6e5a055b-7425-4ba3-b8bf-52484ed1fa0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
