<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_addDet_eventDesc</name>
   <tag></tag>
   <elementGuidId>abfbad6a-a665-46b6-b19c-806e4370fdf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'AdditionalDetails_richTextArea')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.AdditionalDetails_richTextArea__ScSr0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9570e701-9229-45dc-b532-22035d62ab19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AdditionalDetails_richTextArea__ScSr0</value>
      <webElementGuid>06d93eaf-f48d-4e2a-b982-ddab8d81601b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3cc5ce5-56a1-4e88-b86e-b2afeac37ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0b8f7845-c32c-4d95-9791-c67b6b162188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Event description</value>
      <webElementGuid>ac5a09a3-5531-4d09-b31d-00db51aafc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>event-description-char-count</value>
      <webElementGuid>e8b4b2bb-fcd5-45bb-8f9e-63a9534996f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;AdditionalDetails_additionalDetailsWrap__LaU9m&quot;]/div[@class=&quot;AdditionalDetails_pageContainer__8szKE&quot;]/main[@class=&quot;AdditionalDetails_mainContent__aa94b&quot;]/div[@class=&quot;AdditionalDetails_contentInner__tb8pM&quot;]/div[@class=&quot;AdditionalDetails_formSections__7Hp+n&quot;]/section[@class=&quot;AdditionalDetails_section__ciXTu&quot;]/div[@class=&quot;AdditionalDetails_editorCard__h00yy&quot;]/div[@class=&quot;AdditionalDetails_richTextEditorWrap__5Xrhd&quot;]/div[@class=&quot;AdditionalDetails_richTextArea__ScSr0&quot;]</value>
      <webElementGuid>ea95bdfc-f344-49d4-ab9f-073f6d1c22a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div[2]/div[2]/section/div[2]/div[2]/div</value>
      <webElementGuid>5a09121d-cfc0-4a40-bce0-281693673298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Description'])[1]/following::div[7]</value>
      <webElementGuid>f878ad33-97fd-4c01-a864-a41412bdc222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Details'])[2]/following::div[11]</value>
      <webElementGuid>4ba7ed13-6862-4568-b1c5-9caf612918f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parking'])[1]/preceding::div[2]</value>
      <webElementGuid>8bc66708-bb77-469d-8990-8e576d0821b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parking Type'])[1]/preceding::div[4]</value>
      <webElementGuid>aab4d05e-ae2d-48f8-bdad-17f022015d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>ed4e60c3-b1f5-46cb-8d6d-0c74246f611b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
