<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dashboard_Logo</name>
   <tag></tag>
   <elementGuidId>c8608683-3343-40b9-b9de-c232a49e32c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='MarQ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ManagerDashboard_logo__8T-yS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4040f82d-8cfb-4503-b50f-376211492754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/marqLogo.1eae9270ac68df237c58d3cac9a48d9c.svg</value>
      <webElementGuid>5165ce46-8cea-40f9-a3f8-ee27a0a8bbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MarQ</value>
      <webElementGuid>6557cd05-2150-41ff-83ca-3e17321917a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ManagerDashboard_logo__8T-yS</value>
      <webElementGuid>7b008b1d-99d7-435d-af8a-a94cf20b1639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_cont2__ylJGe&quot;]/div[@class=&quot;ManagerDashboard_managerDashboardWrap__ye8Tn&quot;]/div[@class=&quot;ManagerDashboard_container__7WSqw&quot;]/div[@class=&quot;ManagerDashboard_mainContent__kMf7D&quot;]/div[@class=&quot;ManagerDashboard_header__kCLqC&quot;]/div[@class=&quot;ManagerDashboard_headerLeft__xZCQw&quot;]/div[@class=&quot;ManagerDashboard_logo__8T-yS&quot;]/img[@class=&quot;ManagerDashboard_logo__8T-yS&quot;]</value>
      <webElementGuid>c3523ef4-9137-4a66-b524-483c4a1f76e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div/div/img</value>
      <webElementGuid>1069fe1f-b3b7-4d40-a0ec-2950e7308c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MarQ']</value>
      <webElementGuid>cd10d205-6823-498f-ae09-48ac2c036c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>9c69a5cf-3a75-4117-8faf-7d9f8d585bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/marqLogo.1eae9270ac68df237c58d3cac9a48d9c.svg' and @alt = 'MarQ']</value>
      <webElementGuid>d0a0023a-c638-48e9-b1c1-0f085de04db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
