<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notification_button</name>
   <tag></tag>
   <elementGuidId>ebc55998-33ca-48bf-91fb-0dcc8f37d064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ManagerDashboard_notification__Z4Z2r</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b51c32eb-cd02-411b-b30e-daa549e85c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b288498d-6409-458e-baa1-667dd2aca130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ManagerDashboard_notification__Z4Z2r</value>
      <webElementGuid>341d5d0a-c4aa-47af-98d3-8c1ec86042e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>429d7dd7-55cc-4247-a9df-261e1953d6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_cont2__ylJGe&quot;]/div[@class=&quot;ManagerDashboard_managerDashboardWrap__ye8Tn&quot;]/div[@class=&quot;ManagerDashboard_container__7WSqw&quot;]/div[@class=&quot;ManagerDashboard_mainContent__kMf7D&quot;]/div[@class=&quot;ManagerDashboard_header__kCLqC&quot;]/button[@class=&quot;ManagerDashboard_notification__Z4Z2r&quot;]</value>
      <webElementGuid>6d17083c-2f7d-4424-8347-20d6b76c259f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>65297aee-3743-428d-80ef-9c66a7f9018c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>38367524-9d43-427e-b9f3-ccc9e72051fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::button[1]</value>
      <webElementGuid>072f16c3-4741-46fa-a6d4-592997dfd24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data'])[1]/preceding::button[1]</value>
      <webElementGuid>31ef16b2-4958-4d4d-8415-0df248d8b623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>6ade42fc-633d-4c73-a603-c246af6e6b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>3b47c2f0-4161-4fa9-8da1-88f94291fbc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
