<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>1a35899b-9be1-4d69-bf59-d7965d861cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.LogOutModal_deleteBtn__ItsnA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' LogOutModal_deleteBtn__ItsnA ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44533c8f-9972-4f37-9f5f-483363ed7d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>281fddcb-3ea0-4c52-b8ee-80c6e92d3fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LogOutModal_deleteBtn__ItsnA LogOutModal_confirmBtn__+Z5O+ btn btn-primary</value>
      <webElementGuid>9088f1d0-af25-441e-a65a-39ce936f0842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>00078a32-df9b-430c-be9b-9abeef885b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1846e32f5e3c9db44889ac6388ebcf2a</value>
      <webElementGuid>16665319-82c3-4662-a4a1-b20d705d2ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' LogOutModal_deleteBtn__ItsnA ')]</value>
      <webElementGuid>29bad47e-56f4-42fd-844b-dddc2149e655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' LogOutModal_deleteBtn__ItsnA ')]</value>
      <webElementGuid>31bce1f1-10df-4d56-8ead-edc3d19d05e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>a5de42ef-f66e-4036-aec0-2defc2c2d289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
