<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_logIn_loginbtn_LnnFD</name>
   <tag></tag>
   <elementGuidId>abe68f22-24e4-4c3a-97f3-5fc43d33adc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.logIn_loginbtn__LnnFD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' logIn_loginbtn__LnnFD ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84ba97cb-138c-4d65-b642-8f5cde53bb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b8b745f3-8aa0-4c45-8bb9-355586c97812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logIn_loginbtn__LnnFD</value>
      <webElementGuid>7f3b66c9-73df-4e0b-ab4b-fb4e61157720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>cde01e3d-20a0-4a76-991d-c63aa841907e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-577a42a368ee9e7f7f19a1fd719710e0</value>
      <webElementGuid>32ab1dc8-8343-4ea2-9c62-38b2030920ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' logIn_loginbtn__LnnFD ')]</value>
      <webElementGuid>28bd9525-4429-4603-adb7-2d92a4225ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' logIn_loginbtn__LnnFD ')]</value>
      <webElementGuid>d3c951c5-24e5-427b-ac20-2a94be1c4225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>c505ad40-e281-4dcb-8d4f-3adb94ba05a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
