<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Your Password</name>
   <tag></tag>
   <elementGuidId>15c2f2a6-83d0-44a1-af8d-6499fa49741e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'Password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and @id = 'Password' and @placeholder = 'Enter Your Password' and @name = 'Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>546a441c-f8bf-434d-a72b-2befe1980540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6768611e-95fb-4029-bd8e-ed6c21c43bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>db7336a0-e84c-4443-bd34-f24c16cbc8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logIn_emailbox__NHwzv</value>
      <webElementGuid>84f56da2-83af-42c6-bedf-f113c9f76a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Your Password</value>
      <webElementGuid>1006cb7b-081f-4ff8-9157-d4eb4861742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ae1af582-4231-47b0-a1d7-2eb270d4436a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>49761364-3613-4866-a08a-90a7004adb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d159a5c4ad86ab48a0f757ae1d7c12e6</value>
      <webElementGuid>c7ae4a56-761a-4fff-8854-0586b7430318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'Password']</value>
      <webElementGuid>26b85f7d-abd1-4d1e-8bfe-2047397320db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'Password']</value>
      <webElementGuid>ca71f871-1a42-4a72-9aba-7bacbe1e4e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Password' and @placeholder = 'Enter Your Password' and @name = 'Password']</value>
      <webElementGuid>781b295f-e69d-4b59-a653-18bb6b59f3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
