<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address_Selector</name>
   <tag></tag>
   <elementGuidId>ab4841df-1530-40cd-93c4-1a4c5ea47771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[contains(@class, 'suggestion')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0fb8f975-4e2b-4b69-86ff-e6a26c07cbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1775657354422</value>
      <webElementGuid>898aa7a1-ed0c-4962-98e1-a6b386eb917d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
