<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address_Testour</name>
   <tag></tag>
   <elementGuidId>8be7cc66-795d-4ba7-a57d-40e3deff4152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/section[2]/div/div[2]/div/form/div[5]/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.onboarding_card__ph7vv > div:nth-of-type(2) > div:nth-of-type(2) > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c876ec31-a2a4-4662-be84-32f580bdbaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ea8e29b-8f2c-4c31-9c1f-932565deed1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ddf0ab28-6f9e-4c0e-aff0-4f1a056e2523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testour, TunisiaTestour, Béja Governorate</value>
      <webElementGuid>bcba65a3-9702-471c-bcad-b42063cb5c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;onboarding_indexdiv__3S6Pc&quot;]/div[@class=&quot;onboarding_twoColumn__+gxc9&quot;]/section[@class=&quot;onboarding_right__-rkPT&quot;]/div[@class=&quot;onboarding_rightInner__0pQNi&quot;]/div[@class=&quot;onboarding_contentWrap__yQA2l&quot;]/div[@class=&quot;onboarding_contentWrapTwo__Xrz4v&quot;]/form[@class=&quot;onboarding_form__KMRtu&quot;]/div[@class=&quot;onboarding_card__ph7vv&quot;]/div[2]/div[2]/div[1]</value>
      <webElementGuid>035f9362-eab0-497f-a894-dfbe09d077de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/section[2]/div/div[2]/div/form/div[5]/div[2]/div[2]/div</value>
      <webElementGuid>3339a40a-5856-491c-9c1a-f710e7d5a9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[4]</value>
      <webElementGuid>54ab6afe-5b98-46af-8f6d-559ee0dc66fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div</value>
      <webElementGuid>6e27858a-f425-44ff-90ed-90530e8aa7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Testour, TunisiaTestour, Béja Governorate' or . = 'Testour, TunisiaTestour, Béja Governorate')]</value>
      <webElementGuid>e1a1972f-92bd-4cc1-83dd-757a513bb4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
