<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__businessAddress</name>
   <tag></tag>
   <elementGuidId>80c2386e-50fd-4564-99b8-b9429c510b1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#businessAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a9d517c-fc0c-4c56-9f2c-57647e6fd558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessAddress</value>
      <webElementGuid>dd77c8ca-4873-4436-a4de-8763ea0fa5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d665f14-da09-46af-a49a-e261df6309c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onboarding_input__wZCOY onboarding_inputLg__Pxora </value>
      <webElementGuid>5efac476-895b-42ac-ac65-ea283654ccd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing your address...</value>
      <webElementGuid>01d61b7b-7d5f-461c-a055-af6b4cfd6716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Business address</value>
      <webElementGuid>0887e906-9c4d-4a8a-95a2-ea5e4f5c3854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>95ce7ab5-b42b-4503-9188-28b178b489fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessAddress&quot;)</value>
      <webElementGuid>375b96ed-d7eb-417e-b788-e53570e63962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessAddress']</value>
      <webElementGuid>ba6c6f91-2450-46ba-b02e-6d24c3429463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/section[2]/div/div[2]/div/form/div[5]/div[2]/div/input</value>
      <webElementGuid>71251fa3-287c-444d-92f3-baea263b711a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>5a77273a-8904-46b4-890f-cd1e68925f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessAddress' and @type = 'text' and @placeholder = 'Start typing your address...']</value>
      <webElementGuid>ec9ab404-4f69-4b7c-b142-6d73a6c5de0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
