<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sendMessage_attachFile</name>
   <tag></tag>
   <elementGuidId>2f135951-d443-4f89-8da4-8a842c0d23ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Attach file']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Attach\ file&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90cb8945-ce27-44ee-b4a3-bedb72e5d4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0be33585-e00e-4f37-8b3b-a9d742af2fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BulkMessage_attachBtn__GriT3</value>
      <webElementGuid>498dde8b-9d19-4c6d-b12b-f3d627b41503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Attach file</value>
      <webElementGuid>63d12848-1483-4a25-8a6b-22860d20927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Attach file (0/5)</value>
      <webElementGuid>4bdf26bf-979a-40cd-ade0-986147bf9194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attach File</value>
      <webElementGuid>fd583543-acae-4350-b0c6-f78ea6b6cb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-525ce1bc098c1ecfbe91e4c7ba780c62</value>
      <webElementGuid>e4a3343c-4278-41d0-b36a-546b34739219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Attach file']</value>
      <webElementGuid>9367f2be-9f35-4e11-8039-2499cd2b092d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Attach file']</value>
      <webElementGuid>c85e39e5-50cf-4523-b5e2-3bb2f2619415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Attach file (0/5)' and (text() = 'Attach File' or . = 'Attach File')]</value>
      <webElementGuid>d1b77bd2-4471-4b3e-8798-451f2aaeabac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
