<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sendMessage_users</name>
   <tag></tag>
   <elementGuidId>05907c1a-ce11-4d55-a46a-18d5a2047e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' BulkMessage_selectControl__hQgzt ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.BulkMessage_selectControl__hQgzt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cf8e969-9eba-4b12-8537-75459062644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17e5db52-5ea5-4cc5-91ec-b5c815f89b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c731e231-44a7-4993-8f04-2bffce278ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BulkMessage_selectControl__hQgzt</value>
      <webElementGuid>7a48b7ba-f7a1-4f69-8d70-0bfdf32330a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>6d2778dd-4535-4806-9562-41b1ce308aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0a65a1639405a23e401ff899a4feb4f6</value>
      <webElementGuid>ea78c9a4-6c97-4e11-9ee5-ba8dd6aa232b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' BulkMessage_selectControl__hQgzt ')]</value>
      <webElementGuid>c7fa722f-3aca-4464-a0e6-495feb36eaa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' BulkMessage_selectControl__hQgzt ')]</value>
      <webElementGuid>6bf09e64-d336-427a-a375-e9a4998077cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Loading...' or . = 'Loading...')]</value>
      <webElementGuid>9621124e-848b-464b-af14-4795a8165399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
