<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sendMessage_AIAssist</name>
   <tag></tag>
   <elementGuidId>ac53ac89-f125-4c4a-b451-18d04368bea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'AI Assist']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;AI\ Assist&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c22c6b8-773a-45e4-b67e-2cd6d2e535fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d6e2233-c666-493a-8e27-f559fc2b1e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BulkMessage_aiBtn__Hs9OS</value>
      <webElementGuid>28192c1d-9682-4f29-ba89-73fa8b8e2d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AI Assist</value>
      <webElementGuid>7276f778-43bb-40af-bad0-7796715e3f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a2650bd-1111-462d-ba3f-66bb64ee961b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>✨ AI Assist</value>
      <webElementGuid>013d6177-3d9a-4010-bcd3-0d01b7306b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6db1ae39cdd8091c58bf1996192c1318</value>
      <webElementGuid>b9e31c38-18b6-4166-8ed6-03cb9ec78f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'AI Assist']</value>
      <webElementGuid>bbf3bc02-7847-4419-a257-c5894e9e3968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'AI Assist']</value>
      <webElementGuid>32df2db9-9932-41b8-9a60-bf5c15ec6f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '✨ AI Assist' or . = '✨ AI Assist')]</value>
      <webElementGuid>5b7b72cd-a249-42b5-bca5-e1564e3ffce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
