<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Events</name>
   <tag></tag>
   <elementGuidId>209de041-3398-4b07-ba2a-026e502a54e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Events']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Events&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca5b0ea1-a731-4681-8444-787038806d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EventsSidebar_smItem__-I+MJ </value>
      <webElementGuid>1e059b79-fc71-4a64-b1d3-790d7741a784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Events</value>
      <webElementGuid>2b124e92-beef-485e-b4a7-af66a5be3091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Events</value>
      <webElementGuid>126086cd-a4c0-4a9e-a3ba-035f39eae8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-29a99b67697de9d5b477b0d2ba19c600</value>
      <webElementGuid>4125d226-a85e-4439-b7d6-b8f4b46ca046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Events']</value>
      <webElementGuid>99456008-54b9-4c31-913c-a8359c716b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Events']</value>
      <webElementGuid>375a872d-ce77-40d5-b4b7-5ba4c0fb0638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Events' or . = 'Events')]</value>
      <webElementGuid>271ec247-dafd-452c-be50-d49073fc8721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
