<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sendMessage_Send message</name>
   <tag></tag>
   <elementGuidId>e027245f-b1c2-4cf7-8c69-eba84c07260d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Send message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Send\ message&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1dafefae-6850-4901-ab1d-66d094de6157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4558784-3456-416f-abcd-9d646a241835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BulkMessage_sendBtn__TcXIO</value>
      <webElementGuid>a4d0c248-50fe-4e42-a6d2-41d7d7d8333b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Send message</value>
      <webElementGuid>a97bc262-3efc-468e-ba7a-e1d372d6eaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>8d0a35bc-aecb-492b-b980-e8790ab184f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5d2d5c16b7866c2c5730a3f1f25a0322</value>
      <webElementGuid>ede93ad4-40fb-4bd7-8245-84294d8b8db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Send message']</value>
      <webElementGuid>c5a619d0-df72-48b9-8c5a-0a1ecee6b68d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Send message']</value>
      <webElementGuid>df9f01be-d4da-436b-ac9a-7b7224dfab86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>0102edd5-0019-414a-a036-3f3e56e04fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
