<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_raffleConfig_Next</name>
   <tag></tag>
   <elementGuidId>a64b51dd-b3df-43c7-b353-533c5590c93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.RaffleConfiguration_nextButton__pIxGL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bee48903-729f-476c-a1bd-604cbf6f4fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ba93fd1-6d97-42bc-8d0a-6c666f219e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RaffleConfiguration_nextButton__pIxGL</value>
      <webElementGuid>ae456f14-927c-44df-b188-ffd97b2aac28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue to next step</value>
      <webElementGuid>46bf3627-a99d-4dcb-a657-813279343ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>de1288ed-1ccf-47ff-8bf5-a55ec3f49cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;RaffleConfiguration_raffleConfigurationWrap__TPL0u&quot;]/div[@class=&quot;RaffleConfiguration_container__MKqAC&quot;]/main[@class=&quot;RaffleConfiguration_mainContent__zHS6U&quot;]/div[@class=&quot;RaffleConfiguration_mainInner__5Omse&quot;]/div[@class=&quot;RaffleConfiguration_contentWrapper__nZ5pl&quot;]/div[@class=&quot;RaffleConfiguration_actionButtons__rz8Ba&quot;]/div[@class=&quot;RaffleConfiguration_rightButtons__0ZM-+&quot;]/button[@class=&quot;RaffleConfiguration_nextButton__pIxGL&quot;]</value>
      <webElementGuid>43354b86-5769-422b-9127-3468dcf85da0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[66]</value>
      <webElementGuid>17e867af-402d-4a0b-a9ea-e90fdc69d9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[4]/div/button[2]</value>
      <webElementGuid>8a9b8ef0-24db-4fa3-9479-407ba37435d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/following::button[1]</value>
      <webElementGuid>c7be0563-3652-4e68-ba70-c8c3c4e4b7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go Back'])[2]/following::button[2]</value>
      <webElementGuid>a1f472c4-91c7-41dd-95c5-09416796bebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button[2]</value>
      <webElementGuid>e6043e94-ec50-4c35-9964-7eb64e2cc217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>1543a836-3279-4186-bbae-347b86bd9542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
