<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pricePerTicket</name>
   <tag></tag>
   <elementGuidId>ac380ba0-4f6b-49d1-a8dd-1e618c6ca63a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pricePerTicket</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pricePerTicket']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7ad03b1-51d4-48ba-8894-44cb46f84481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pricePerTicket</value>
      <webElementGuid>700488fa-4a5a-4fe2-88b6-c5126dd2583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d55591f-8469-4c39-8c87-46d7b53854e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>dc8d08e2-5a26-48e2-a582-ec5e7c11c735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4ce4e13f-17e0-427a-9bc2-3eda07ad5222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RaffleConfiguration_formInput__DfO4b RaffleConfiguration_withPrefix__camZI </value>
      <webElementGuid>fdc137d9-2f08-4a47-b30b-cdb29d1a3a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>42645b11-bde6-4cb0-8ac0-3db0346aaa35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pricePerTicket&quot;)</value>
      <webElementGuid>f55c02d0-8220-4efd-b4f3-1e9746d78efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pricePerTicket']</value>
      <webElementGuid>69816c8c-07c4-4eb7-b333-7fbd99d86b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>2eeb41b5-e9cc-4690-a4fd-e984bddd8a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0dd11f24-99aa-43bf-9aad-614dc502d30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pricePerTicket' and @type = 'text']</value>
      <webElementGuid>d76b4595-e7ab-4f38-8ade-11463420666d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
