<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__totalTicketsAvailable</name>
   <tag></tag>
   <elementGuidId>98331950-0089-4a9e-b174-91ccb087686f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalTicketsAvailable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalTicketsAvailable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2199e7fe-a519-4838-9260-b45e846ef52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalTicketsAvailable</value>
      <webElementGuid>88037db7-6594-4a31-9e35-0d4ce8c1d99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2f0a380-77be-488f-80ca-86bf1cf714c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RaffleConfiguration_formInput__DfO4b </value>
      <webElementGuid>04b50272-78a0-45cd-ad6f-53b0d240fbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>def32219-1e27-441e-9656-87f5fd3d03e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7786203-6bf3-4251-8396-c5b6aa3fd801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalTicketsAvailable&quot;)</value>
      <webElementGuid>0417004c-4dab-4023-8928-6764b8db8663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalTicketsAvailable']</value>
      <webElementGuid>c43b3e04-0d7e-4527-ae9a-fd27cac576ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[3]/div/div/div[4]/input</value>
      <webElementGuid>9ed310f2-de1b-4ccd-9fce-289950fb1a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d06cd8a0-584b-4410-9954-2049502c5307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'totalTicketsAvailable' and @type = 'text' and @placeholder = '500']</value>
      <webElementGuid>96c16c44-43bd-4063-af18-af0aa96e7581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
