<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_raffle_drawDate</name>
   <tag></tag>
   <elementGuidId>964c074c-fd47-49ae-aeeb-bc77a7ba2788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-date-picker__inputGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5acc707f-ab18-475f-9c01-3d57842a340c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-date-picker__inputGroup</value>
      <webElementGuid>bbda854a-4f11-4901-a5f9-51cf62a6e1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--</value>
      <webElementGuid>9f3343c1-45fb-4f3d-a7d0-cd7b36fed017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;RaffleConfiguration_raffleConfigurationWrap__TPL0u&quot;]/div[@class=&quot;RaffleConfiguration_container__MKqAC&quot;]/main[@class=&quot;RaffleConfiguration_mainContent__zHS6U&quot;]/div[@class=&quot;RaffleConfiguration_mainInner__5Omse&quot;]/div[@class=&quot;RaffleConfiguration_contentWrapper__nZ5pl&quot;]/div[@class=&quot;RaffleConfiguration_contentWrapper__nZ5pl&quot;]/div[@class=&quot;RaffleConfiguration_formSection__5775o&quot;]/div[@class=&quot;RaffleConfiguration_formGroup__4MNpL RaffleConfiguration_formGroupWrap__168eF&quot;]/div[@class=&quot;RaffleConfiguration_dateTimeRow__u3BMk&quot;]/div[@class=&quot;RaffleConfiguration_dateInputWrapper__uWwPE&quot;]/div[@class=&quot;RaffleConfiguration_inputWithIcon__a2oqR&quot;]/div[@class=&quot;react-date-picker react-date-picker--closed react-date-picker--enabled RaffleConfiguration_datePickerRoot__zyS5q&quot;]/div[@class=&quot;react-date-picker__wrapper&quot;]/div[@class=&quot;react-date-picker__inputGroup&quot;]</value>
      <webElementGuid>866c5887-ac40-46f8-8315-e635330b2c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[3]/div/div[2]/div[3]/div/div/div/div/div</value>
      <webElementGuid>5e66bb14-ee77-4f37-82b3-37440b161696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom date &amp; time'])[1]/following::div[6]</value>
      <webElementGuid>a060197a-808b-4464-93df-94fca5b14175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After Event'])[1]/following::div[6]</value>
      <webElementGuid>88dcaca5-2665-4e20-844c-bc83b8ea1ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div/div</value>
      <webElementGuid>6d2badc6-ef39-4d3e-9a9e-c46eed3f4ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '--' or . = '--')]</value>
      <webElementGuid>0c4d76cd-bb41-45a3-97f5-33aa3233e278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
