<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum Tickets per User_maxTicketsPerUser</name>
   <tag></tag>
   <elementGuidId>bf33aeec-4850-42a1-b029-8ccf17c5ed12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxTicketsPerUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxTicketsPerUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2308a16c-34e2-417d-b33b-cdc44031244b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxTicketsPerUser</value>
      <webElementGuid>2352b1ee-066d-46b1-8480-58ed9f78ebde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>134267da-a9b4-44fc-a485-81143b0a15aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>9ceff3b3-3478-473b-bd28-537ac488972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>785a945c-fcfa-4ccf-a60c-11c40fd63515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RaffleConfiguration_formInput__DfO4b</value>
      <webElementGuid>448147fe-d0bb-43ca-a3b2-0d05c5e48809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e6b76b00-d883-4087-bf51-68881aced6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Maximum tickets per user (numbers only)</value>
      <webElementGuid>c33d328a-e195-402e-afb4-89d5e99e5d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxTicketsPerUser&quot;)</value>
      <webElementGuid>a567f708-c201-4873-a47a-0513dd46c2ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxTicketsPerUser']</value>
      <webElementGuid>02f97465-2182-445b-a51c-ba8f46a0f1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[3]/div/div/div[3]/input</value>
      <webElementGuid>1ffacf13-0f5b-441b-83e9-e3bf85739852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>417491b7-dddd-40f9-89c1-dbeca159bd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxTicketsPerUser' and @type = 'text' and @placeholder = '10']</value>
      <webElementGuid>5d8ae1d8-249f-4a11-a54a-7395a42d8b65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
