<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_raffleConfig_required</name>
   <tag></tag>
   <elementGuidId>aee4ff17-7821-4bd9-83fc-4dd8a031c349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.RaffleConfiguration_checkbox__RFHTB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cacc6258-ef2b-45df-8eb7-048aed31cb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a260e7b4-88f7-4052-8c43-a1a32bb6ae48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RaffleConfiguration_checkbox__RFHTB </value>
      <webElementGuid>4191196b-e13b-4270-ae06-f7cb37635b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d8931f7-4403-4c29-880c-e97a83ba9535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;CancelTicket_bodythemeNew__paE0E&quot;]/div[@class=&quot;CancelTicket_dashboard__5u4hM&quot;]/div[@class=&quot;RaffleConfiguration_raffleConfigurationWrap__TPL0u&quot;]/div[@class=&quot;RaffleConfiguration_container__MKqAC&quot;]/main[@class=&quot;RaffleConfiguration_mainContent__zHS6U&quot;]/div[@class=&quot;RaffleConfiguration_mainInner__5Omse&quot;]/div[@class=&quot;RaffleConfiguration_contentWrapper__nZ5pl&quot;]/div[@class=&quot;RaffleConfiguration_contentWrapper__nZ5pl&quot;]/div[@class=&quot;RaffleConfiguration_formSection__5775o&quot;]/div[@class=&quot;RaffleConfiguration_complianceCheckbox__i5pc4&quot;]/label[@class=&quot;RaffleConfiguration_checkboxLabel__HGbA9&quot;]/input[@class=&quot;RaffleConfiguration_checkbox__RFHTB&quot;]</value>
      <webElementGuid>576b657b-557c-442a-b7d1-231740201103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>0f46f1f9-a4a1-45d3-b167-ec32d20ec2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[3]/div[3]/div[3]/label/input</value>
      <webElementGuid>75df7e8f-6890-4d1e-81c6-d83d6817042a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>0722bcd8-60f0-4d1e-9353-ddf2c38b1875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b99cfa5c-628c-4a37-9580-bc0d5606101e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
