<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__raffleTicketName</name>
   <tag></tag>
   <elementGuidId>cfaed16e-38e5-4c8d-888f-4f1f2f40007c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#raffleTicketName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='raffleTicketName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08d07638-4adb-4ec1-b865-a888871f4617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>raffleTicketName</value>
      <webElementGuid>c2afaa2b-0f1d-4581-91de-5d1aafe1ee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbd1616c-5beb-4576-a43a-82cd48378ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RaffleConfiguration_formInput__DfO4b </value>
      <webElementGuid>2a1fca40-2b27-4221-8b70-6108721ff560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>488103e7-a785-489c-aac1-d7d104a659d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;raffleTicketName&quot;)</value>
      <webElementGuid>0277c12b-7019-40ed-95f7-70c443147e7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='raffleTicketName']</value>
      <webElementGuid>36b29514-9591-4458-8e78-5b8efae048a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/main/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>b37aec52-a39c-4d68-9283-f8e6a5dd471e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>15e5618a-53cc-48af-980c-3b070ad7138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'raffleTicketName' and @type = 'text']</value>
      <webElementGuid>eaf8d9ad-10e1-4e75-9bfa-0b0fba8feef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
