<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Privacy Policy_register_loginbtn__-y0Yl</name>
   <tag></tag>
   <elementGuidId>be091ca5-7f6d-4589-bb9d-c15dfe9aa16a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register_loginbtn__-y0Yl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register_loginbtn__-y0Yl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97b3ba3b-733b-4472-b6de-ffecfa10c869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c16bf9ce-65d1-4cfc-b0ad-bd7b896b5a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_loginbtn__-y0Yl</value>
      <webElementGuid>c6bfaf7c-9bed-4995-ae9f-4070b0e5b950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>8d695597-c24d-48fd-bc8a-1bcc1ec39786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_loginbtn__-y0Yl&quot;)</value>
      <webElementGuid>4bcd038f-c294-4007-b176-3e16cdc2cbaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register_loginbtn__-y0Yl']</value>
      <webElementGuid>06e56a4e-6f6f-426d-a41d-fb0a24169b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/input</value>
      <webElementGuid>8719ee79-a2fb-4d4c-add0-5cf4263a3f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>892ec563-1a38-46c4-855b-d812d2c38ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'register_loginbtn__-y0Yl']</value>
      <webElementGuid>770bb392-2f9a-444b-abc4-f1befc4f10ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
