<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Resend Code_otpVerify_loginbtn__wOnJC</name>
   <tag></tag>
   <elementGuidId>848d7d24-f6f8-419c-a665-1f8f28a564b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otpVerify_loginbtn__wOnJC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otpVerify_loginbtn__wOnJC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>674d176c-ef7b-4cd6-862b-c38a39e5b2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a8de64da-afb0-4639-b2f3-020ffe6096c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otpVerify_loginbtn__wOnJC</value>
      <webElementGuid>e3d318bd-434b-4559-8dbc-859955eff782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verify Now</value>
      <webElementGuid>2b9e231b-6323-45c8-b03d-1c40ae8ed00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otpVerify_loginbtn__wOnJC&quot;)</value>
      <webElementGuid>68185784-66e0-4f62-bfb2-57dca800715b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otpVerify_loginbtn__wOnJC']</value>
      <webElementGuid>97e0ef3a-6977-4b8e-9070-13098b145ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/input[2]</value>
      <webElementGuid>fedcabab-676f-4759-8cca-de10bc7b1892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>15a60eea-6f1a-4337-a00e-d2d30f61833b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'otpVerify_loginbtn__wOnJC']</value>
      <webElementGuid>d9f94660-f713-4373-9853-70b31ef66b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
