<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Stall Name</name>
   <tag></tag>
   <elementGuidId>cb71a144-7499-4e2f-a2f5-966e25c317f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'vendor-businessName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vendor-businessName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c40bcc2e-7825-47e4-a13a-972a81ac92e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessName</value>
      <webElementGuid>6c70cfd5-1440-4fd7-8b3a-02a8bab3f4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Stall Name</value>
      <webElementGuid>eb716841-5db8-4cd6-8303-d15e3b8935aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>1018d94e-f137-4a67-b9af-aa83e764fc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95015463-17af-453b-8f6b-c36efc9ed62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a516d63f-f1e8-4d7e-8106-0efb93e6db71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vendor-businessName</value>
      <webElementGuid>2fa8407d-9e3c-45e0-ae6c-6c3ad6f038dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3f4de97-c2c1-49a7-b780-6e468b559a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0617ef4326b4acc4f804d9d82054a275</value>
      <webElementGuid>821ffe66-1b0e-4f1b-8454-0b0e34437d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'vendor-businessName']</value>
      <webElementGuid>ebd132e8-d9a0-474b-9b1f-cd59c9be6ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'vendor-businessName']</value>
      <webElementGuid>fd8df5db-66ec-4fa1-b968-4c41a2fcd716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'businessName' and @placeholder = 'Enter Stall Name' and @type = 'text' and @id = 'vendor-businessName']</value>
      <webElementGuid>c8cbc6a7-f7a3-4c6a-9842-12eac659d2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
